DROP TABLE IF EXISTS pf_park_factors;

CREATE TABLE pf_park_factors (
  groupingId INTEGER,
  groupingDescription TEXT,
  majorLeagueId INTEGER,
  seasonId REAL,
  venueId INTEGER,
  teamId INTEGER,
  homeGames INTEGER,
  awayGames INTEGER,
  runsScoredHome INTEGER,
  runsAllowedHome INTEGER,
  runsScoredAway INTEGER,
  runsAllowedAway INTEGER,
  singlesScoredHome INTEGER,
  singlesAllowedHome INTEGER,
  singlesScoredAway INTEGER,
  singlesAllowedAway INTEGER,
  doublesScoredHome INTEGER,
  doublesAllowedHome INTEGER,
  doublesScoredAway INTEGER,
  doublesAllowedAway INTEGER,
  triplesScoredHome INTEGER,
  triplesAllowedHome INTEGER,
  triplesScoredAway INTEGER,
  triplesAllowedAway INTEGER,
  homeRunsScoredHome INTEGER,
  homeRunsAllowedHome INTEGER,
  homeRunsScoredAway INTEGER,
  homeRunsAllowedAway INTEGER,
  strikeOutsScoredHome INTEGER,
  strikeOutsAllowedHome INTEGER,
  strikeOutsScoredAway INTEGER,
  strikeOutsAllowedAway INTEGER,
  unintentionalWalksScoredHome INTEGER,
  unintentionalWalksAllowedHome INTEGER,
  unintentionalWalksScoredAway INTEGER,
  unintentionalWalksAllowedAway INTEGER,
  flyBallsScoredHome INTEGER,
  flyBallsAllowedHome INTEGER,
  flyBallsScoredAway INTEGER,
  flyBallsAllowedAway INTEGER,
  groundBallsScoredHome INTEGER,
  groundBallsAllowedHome INTEGER,
  groundBallsScoredAway INTEGER,
  groundBallsAllowedAway INTEGER,
  lineDrivesScoredHome INTEGER,
  lineDrivesAllowedHome INTEGER,
  lineDrivesScoredAway INTEGER,
  lineDrivesAllowedAway INTEGER,
  runsParkFactor REAL,
  singlesParkFactor REAL,
  doublesParkFactor REAL,
  triplesParkFactor REAL,
  homeRunsParkFactor REAL,
  strikeOutsParkFactor REAL,
  unintentionalWalksParkFactor REAL,
  flyBallsParkFactor REAL,
  groundBallsParkFactor REAL,
  lineDrivesParkFactor REAL,
  -- Atributos
  majorLeague TEXT,
  venueName TEXT
);

CREATE INDEX IF NOT EXISTS idx_pf_park_factors_groupingId ON pf_park_factors(groupingId);
CREATE INDEX IF NOT EXISTS idx_pf_park_factors_groupingDescription ON pf_park_factors(groupingDescription);
CREATE INDEX IF NOT EXISTS idx_pf_park_factors_majorLeagueId ON pf_park_factors(majorLeagueId);
CREATE INDEX IF NOT EXISTS idx_pf_park_factors_seasonId ON pf_park_factors(seasonId);
CREATE INDEX IF NOT EXISTS idx_pf_park_factors_venueId ON pf_park_factors(venueId);
