DROP TABLE IF EXISTS stg_box_team;

CREATE TABLE IF NOT EXISTS stg_box_team (
  abbreviation TEXT,
  active INTEGER,
  allStarStatus TEXT,
  fileCode TEXT,
  firstYearOfPlay TEXT,
  locationName TEXT,
  parentOrgId INTEGER,
  parentOrgName TEXT,
  season INTEGER,
  shortName TEXT,
  teamCode TEXT,
  teamName TEXT,
  id INTEGER,
  name TEXT,
  link TEXT,
  leagueId INTEGER,
  leagueName TEXT,
  leagueLink TEXT,
  venueId INTEGER,
  venueName TEXT,
  venueLink TEXT,
  divisionId INTEGER,
  divisionName TEXT,
  divisionLink TEXT,
  gamePk INTEGER,
  teamId INTEGER,
  teamType TEXT
);
