"""
agg_team_performance_stats_sqlite.py
──────────────────────────────────────
Equivalent of the MySQL CALL agg_team_performance_stats(...) cube inserts,
rewritten as static SQL for SQLite3.

Notable: the CTE uses a UNION ALL on games to produce both the home and
away perspective in a single pass — no extra source tables needed.

groupingId   → SHA-256 of sorted field names (first 8 hex digits as int)
groupingDesc → field names uppercased, joined by '_'

Usage:
    python agg_team_performance_stats_sqlite.py [--output agg_team_performance_stats.sql]
"""

import argparse
import hashlib

# ── All possible dimension columns (order = INSERT column order) ─────────────
ALL_DIMS = [
    "majorLeagueId",
    "seasonId",
    "gameType2",
    "teamId",
    "teamType",
    "venueId",
]

# ── Groupings — direct translation of each CALL ──────────────────────────────
GROUPINGS = [
    {"fields": ["majorLeagueId", "seasonId", "gameType2", "teamId"]},
    {"fields": ["majorLeagueId", "seasonId", "gameType2", "teamId", "teamType"]},
]

# ── Stat columns (order matches INSERT target table) ─────────────────────────
STAT_COLS = ["runs", "runsAllowed", "wins", "losses", "attendance"]


def grouping_id(fields: list[str]) -> int:
    """Stable integer ID: SHA-256 of sorted field names, first 8 hex digits as uint."""
    key = ",".join(sorted(fields))
    return int(hashlib.sha256(key.encode()).hexdigest()[:8], 16)


def grouping_desc(fields: list[str]) -> str:
    """e.g. ["majorLeagueId", "seasonId"] → "MAJORLEAGUEID_SEASONID" """
    return "_".join(f.upper() for f in fields)


def build_cte(active_fields: list[str]) -> str:
    """
    UNION ALL CTE that produces home + away rows from games,
    then 'd' groups by the active fields.
    """
    group_by_inner = ", ".join(active_fields)

    # Dimension SELECT expressions inside 'd'.
    # All dims are available in the 'g' CTE by name.
    dim_exprs_inner = [
        col if col in active_fields else f"NULL AS {col}"
        for col in ALL_DIMS
    ]
    dim_select_inner = ",\n        ".join(dim_exprs_inner)

    return f"""
WITH g AS (
    SELECT
        majorLeagueId, seasonId, gameDate, gameType2,
        'home'      AS teamType,
        venueId,
        homeTeamId  AS teamId,
        homeScore   AS runs,
        awayScore   AS runsAllowed,
        CASE WHEN homeIsWinner = 1 THEN 1 ELSE 0 END AS wins,
        CASE WHEN awayIsWinner = 1 THEN 1 ELSE 0 END AS losses,
        attendance
    FROM games

    UNION ALL

    SELECT
        majorLeagueId, seasonId, gameDate, gameType2,
        'away'      AS teamType,
        venueId,
        awayTeamId  AS teamId,
        awayScore   AS runs,
        homeScore   AS runsAllowed,
        CASE WHEN awayIsWinner = 1 THEN 1 ELSE 0 END AS wins,
        CASE WHEN homeIsWinner = 1 THEN 1 ELSE 0 END AS losses,
        attendance
    FROM games
),
d AS (
    SELECT
        {dim_select_inner},
        SUM(runs)        AS runs,
        SUM(runsAllowed) AS runsAllowed,
        SUM(wins)        AS wins,
        SUM(losses)      AS losses,
        SUM(attendance)  AS attendance
    FROM g
    WHERE gameType2 IN ('RS', 'PS')
    GROUP BY {group_by_inner}
)"""


def build_select_exprs(active_fields: list[str]) -> list[str]:
    dim_exprs  = [
        col if col in active_fields else f"NULL AS {col}"
        for col in ALL_DIMS
    ]
    stat_exprs = [f"SUM({col}) AS {col}" for col in STAT_COLS]
    return dim_exprs + stat_exprs


def build_insert(grouping: dict) -> str:
    active = grouping["fields"]
    gid    = grouping_id(active)
    gdesc  = grouping_desc(active)

    all_target_cols = ALL_DIMS + ["aggregationType"] + STAT_COLS + ["groupingId", "groupingDescription"]
    select_exprs    = build_select_exprs(active)
    group_by        = ", ".join(active)

    cols_str    = ",\n        ".join(all_target_cols)
    selects_str = ",\n        ".join(select_exprs)

    return f"""
-- ── Grouping {gid}: {gdesc} ──────────────────────────────────────────────
INSERT INTO agg_team_performance_stats (
        {cols_str}
)
{build_cte(active).strip()}
SELECT
        {selects_str},
        'AGGREGATED' AS aggregationType,
        {gid}        AS groupingId,
        '{gdesc}'    AS groupingDescription
FROM d
GROUP BY {group_by};
"""


def generate_sql_file(output_path: str) -> None:
    header = """\
-- ============================================================
-- agg_team_performance_stats cube — SQLite3 static equivalent
-- Generated by agg_team_performance_stats_sqlite.py
-- Run with:  sqlite3 your_base.db < agg_team_performance_stats.sql
-- ============================================================

BEGIN;
"""
    footer = "\nCOMMIT;\n"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
        for grouping in GROUPINGS:
            f.write(build_insert(grouping))
            f.write("\n")
        f.write(footer)

    print(f"✓ SQL file written to: {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate agg_team_performance_stats cube SQL for SQLite3"
    )
    parser.add_argument(
        "--output", required=False,
        default="../batting/team_performance/agg_team_performance_stats.sql",
        help="Output .sql file path (default: agg_team_performance_stats.sql)",
    )
    args = parser.parse_args()
    generate_sql_file(args.output)
