"""
update_table_attributes_sqlite.py
───────────────────────────────────
Equivalent of the MySQL CALL update_table_attributes(...) statements,
rewritten as static SQL for SQLite3.

Key differences from MySQL:
  - No UPDATE ... JOIN syntax in SQLite → replaced with UPDATE ... SET col = (subquery)
  - No CONTINUE HANDLER for SQLEXCEPTION → each UPDATE is wrapped in a
    savepoint so a missing column silently rolls back just that statement
    when executed via the Python runner (--execute mode).
  - CONCAT(firstName, " ", lastName) → firstName || ' ' || lastName

Two modes:
  --output   (default) Generate a .sql file
  --execute  Run directly against a SQLite3 database, skipping statements
             that fail (equivalent to MySQL's CONTINUE HANDLER behaviour)

Usage:
    python update_table_attributes_sqlite.py [--output update_table_attributes.sql]
    python update_table_attributes_sqlite.py --execute --db path/to/your.db
"""

import argparse
import sqlite3

# ── Tables to update (in order of original CALL sequence) ────────────────────
TABLES = [
    "agg_batting_stats",
    "agg_pitching_split_stats",
    "agg_pitching_stats",
    "agg_pitching_balls_in_play_heatmaps",
    "agg_fielding_stats",
    "pf_park_factors",
    "pf_heat_map_park_factors",
    "agg_team_performance_stats",
]

# ── Update definitions ────────────────────────────────────────────────────────
# Each entry is a (label, sql_template) pair.
# {tbl} is replaced with the table name at generation time.
UPDATES = [
    (
        "majorLeague",
        """UPDATE {tbl}
SET majorLeague = (
    SELECT majorLeague
    FROM games
    WHERE games.majorLeagueId = {tbl}.majorLeagueId
    LIMIT 1
)
WHERE EXISTS (
    SELECT 1 FROM games WHERE games.majorLeagueId = {tbl}.majorLeagueId
);""",
    ),
    (
        "playerName",
        """UPDATE {tbl}
SET playerName = (
    SELECT firstName || ' ' || lastName
    FROM players
    WHERE players.playerId = {tbl}.playerId
    LIMIT 1
)
WHERE {tbl}.playerId IS NOT NULL;""",
    ),
    (
        "teamName",
        """UPDATE {tbl}
SET teamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = {tbl}.majorLeagueId
      AND games.seasonId      = {tbl}.seasonId
      AND games.homeTeamId    = {tbl}.teamId
    LIMIT 1
)
WHERE {tbl}.teamId IS NOT NULL;""",
    ),
    (
        "venueName",
        """UPDATE {tbl}
SET venueName = (
    SELECT venueName
    FROM games
    WHERE games.venueId = {tbl}.venueId
    LIMIT 1
)
WHERE {tbl}.venueId IS NOT NULL;""",
    ),
    (
        "officialName",
        """UPDATE {tbl}
SET officialName = (
    SELECT firstName || ' ' || lastName
    FROM officials
    WHERE officials.officialId = {tbl}.officialId
    LIMIT 1
)
WHERE {tbl}.officialId IS NOT NULL;""",
    ),
    (
        "opposingTeamName",
        """UPDATE {tbl}
SET opposingTeamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = {tbl}.majorLeagueId
      AND games.seasonId      = {tbl}.seasonId
      AND games.homeTeamId    = {tbl}.teamId
    LIMIT 1
)
WHERE {tbl}.teamId IS NOT NULL;""",
    ),
]


def build_table_block(tbl: str) -> str:
    """Build all UPDATE statements for one table, wrapped in savepoints."""
    lines = [f"\n-- ── {tbl} {'─' * max(1, 60 - len(tbl))}"]
    for label, template in UPDATES:
        sql = template.format(tbl=tbl)
        lines.append(f"\n-- {label}")
        # Each statement in its own savepoint so a missing column rolls back
        # only that statement (mirrors MySQL's CONTINUE HANDLER behaviour).
        lines.append(f"SAVEPOINT before_{tbl}_{label};")
        lines.append(sql)
        lines.append(f"RELEASE SAVEPOINT before_{tbl}_{label};")
    return "\n".join(lines)


def generate_sql_file(output_path: str) -> None:
    header = """\
-- ============================================================
-- update_table_attributes — SQLite3 static equivalent
-- Generated by update_table_attributes_sqlite.py
--
-- Each UPDATE is wrapped in a SAVEPOINT so that statements
-- referencing columns that don't exist in a given table are
-- rolled back silently (equivalent to MySQL's CONTINUE HANDLER).
--
-- Run with:  sqlite3 your_base.db < update_table_attributes.sql
-- ============================================================

BEGIN;
"""
    footer = "\nCOMMIT;\n"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
        for tbl in TABLES:
            f.write(build_table_block(tbl))
            f.write("\n")
        f.write(footer)

    print(f"✓ SQL file written to: {output_path}")


def execute_against_db(db_path: str) -> None:
    """
    Run all updates against a live SQLite3 database.
    Each (table, attribute) pair is attempted independently;
    failures (e.g. column does not exist) are skipped with a warning.
    """
    con = sqlite3.connect(db_path)
    total = ok = skipped = 0

    try:
        for tbl in TABLES:
            print(f"\n── {tbl}")
            for label, template in UPDATES:
                sql = template.format(tbl=tbl)
                total += 1
                try:
                    con.execute("BEGIN")
                    con.execute(sql)
                    con.execute("COMMIT")
                    print(f"   ✓ {label}")
                    ok += 1
                except sqlite3.OperationalError as e:
                    con.execute("ROLLBACK")
                    print(f"   ⚠ {label} skipped: {e}")
                    skipped += 1
    finally:
        con.close()

    print(f"\n✓ Done — {ok}/{total} updated, {skipped} skipped.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Apply update_table_attributes logic to SQLite3"
    )
    parser.add_argument(
        "--output", required=False,
        default="update_table_attributes.sql",
        help="Output .sql file path (default: update_table_attributes.sql)",
    )
    parser.add_argument(
        "--execute", action="store_true",
        help="Execute directly against a database instead of writing a .sql file",
    )
    parser.add_argument(
        "--db", required=False,
        help="Path to SQLite3 database (required with --execute)",
    )
    args = parser.parse_args()

    if args.execute:
        if not args.db:
            parser.error("--execute requires --db")
        execute_against_db(args.db)
    else:
        generate_sql_file(args.output)
