-- ============================================================
-- agg_batting_stats cube — SQLite3 static equivalent
-- Run with:  sqlite3 your_base.db < agg_batting_stats.sql
-- ============================================================

BEGIN;

-- ── Grouping 4186695649: MAJORLEAGUEID_SEASONID_GAMETYPE2 ──────────────────────────────────────────────
INSERT INTO agg_batting_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        venueId,
        officialId,
        opposingTeamId,
        atbats,
        balks,
        batterInterferences,
        bunts,
        catcherInterferences,
        doubles,
        fanInterferences,
        fieldErrors,
        fieldersChoice,
        flyouts,
        forceOuts,
        games,
        groundedIntoDoublePlays,
        groundedIntoTriplePlays,
        groundOuts,
        hitByPitch,
        hits,
        homeRuns,
        intentionalWalks,
        lineOuts,
        passedBalls,
        popOuts,
        runsBattedIn,
        sacBunts,
        sacFlies,
        singles,
        strikeOuts,
        triples,
        walks,
        wildPitches,
        balls,
        ballsPitchOut,
        ballsInDirt,
        intentBalls,
        fouls,
        foulBunts,
        foulTips,
        foulPitchOuts,
        hitIntoPlay,
        pitches,
        pitchOuts,
        strikes,
        strikesCalled,
        strikesPitchOuts,
        missedBunts,
        swingAndMissStrikes,
        swingsPitchOuts,
        swings,
        swingsZeroAndZero,
        swingsZeroAndOne,
        swingsZeroAndTwo,
        swingsOneAndZero,
        swingsOneAndOne,
        swingsOneAndTwo,
        swingsTwoAndZero,
        swingsTwoAndOne,
        swingsTwoAndTwo,
        swingsThreeAndZero,
        swingsThreeAndOne,
        swingsThreeAndTwo,
        flyBalls,
        groundBalls,
        lineDrives,
        popUps,
        groundBunts,
        popupBunts,
        lineDriveBunts,
        groupingId,
        groupingDescription
)
WITH bs AS (
    SELECT *, pitchingTeamId AS opposingTeamId
    FROM game_player_split_stats
),
g AS (
    SELECT majorLeagueId, seasonId, gamePk, gameType2, venueId, homeTeamId
    FROM games
    WHERE gameType2 IN ('PS', 'RS')
),
officials AS (
    SELECT gamePk, officialId
    FROM game_officials
    WHERE position = 'Home Plate'
),
data AS (
    SELECT
        g.majorLeagueId, g.seasonId, g.gamePk, g.gameType2, g.venueId,
        CASE WHEN g.homeTeamId = bs.battingTeamId THEN 'home' ELSE 'away' END AS teamType,
        bs.battingTeamId  AS teamId,
        bs.batterId       AS playerId,
        bs.opposingTeamId,
        o.officialId,
        batSide, pitchHand, menOnBase,
        (batterInterferences + bunts + doubles + fanInterferences + fieldErrors
         + fieldersChoice + flyouts + forceOuts + groundedIntoDoublePlays
         + triplePlays + groundOuts + homeRuns + lineOuts + popOuts
         + singles + strikeOuts + triples) AS atbats,
        balks, batterInterferences, bunts, catcherInterferences, doubles,
        fanInterferences, fieldErrors, fieldersChoice, flyouts, forceOuts,
        groundedIntoDoublePlays, groundOuts, hitByPitch, homeRuns,
        intentionalWalks, lineOuts, passedBalls, popOuts, runsBattedIn,
        sacBunts, sacFlies, singles, strikeOuts, triples, triplePlays,
        walks, wildPitches,
        balls, ballsPitchOut, ballsInDirt, intentBalls, fouls, foulBunts,
        foulTips, foulPitchOuts, hitIntoPlay, pitches, pitchOuts, strikes,
        strikesCalled, strikesPitchOuts, missedBunts, swingAndMissStrikes,
        swingsPitchOuts, swings,
        swingsZeroAndZero, swingsZeroAndOne, swingsZeroAndTwo,
        swingsOneAndZero,  swingsOneAndOne,  swingsOneAndTwo,
        swingsTwoAndZero,  swingsTwoAndOne,  swingsTwoAndTwo,
        swingsThreeAndZero,swingsThreeAndOne, swingsThreeAndTwo,
        flyBalls, groundBalls, lineDrives, popUps,
        groundBunts, popupBunts, lineDriveBunts
    FROM g
    INNER JOIN bs       ON g.gamePk = bs.gamePk
    LEFT  JOIN officials o ON g.gamePk = o.gamePk
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        NULL AS teamId,
        NULL AS teamType,
        NULL AS playerId,
        NULL AS venueId,
        NULL AS officialId,
        NULL AS opposingTeamId,
        SUM(atbats)                AS atbats,
        SUM(balks)                 AS balks,
        SUM(batterInterferences)   AS batterInterferences,
        SUM(bunts)                 AS bunts,
        SUM(catcherInterferences)  AS catcherInterferences,
        SUM(doubles)               AS doubles,
        SUM(fanInterferences)      AS fanInterferences,
        SUM(fieldErrors)           AS fieldErrors,
        SUM(fieldersChoice)        AS fieldersChoice,
        SUM(flyouts)               AS flyouts,
        SUM(forceOuts)             AS forceOuts,
        COUNT(DISTINCT gamePk)     AS games,
        SUM(groundedIntoDoublePlays) AS groundedIntoDoublePlays,
        SUM(triplePlays)           AS groundedIntoTriplePlays,
        SUM(groundOuts)            AS groundOuts,
        SUM(hitByPitch)            AS hitByPitch,
        SUM(singles)+SUM(doubles)+SUM(triples)+SUM(homeRuns) AS hits,
        SUM(homeRuns)              AS homeRuns,
        SUM(intentionalWalks)      AS intentionalWalks,
        SUM(lineOuts)              AS lineOuts,
        SUM(passedBalls)           AS passedBalls,
        SUM(popOuts)               AS popOuts,
        SUM(runsBattedIn)          AS runsBattedIn,
        SUM(sacBunts)              AS sacBunts,
        SUM(sacFlies)              AS sacFlies,
        SUM(singles)               AS singles,
        SUM(strikeOuts)            AS strikeOuts,
        SUM(triples)               AS triples,
        SUM(walks)                 AS walks,
        SUM(wildPitches)           AS wildPitches,
        SUM(balls)                 AS balls,
        SUM(ballsPitchOut)         AS ballsPitchOut,
        SUM(ballsInDirt)           AS ballsInDirt,
        SUM(intentBalls)           AS intentBalls,
        SUM(fouls)                 AS fouls,
        SUM(foulBunts)             AS foulBunts,
        SUM(foulTips)              AS foulTips,
        SUM(foulPitchOuts)         AS foulPitchOuts,
        SUM(hitIntoPlay)           AS hitIntoPlay,
        SUM(pitches)               AS pitches,
        SUM(pitchOuts)             AS pitchOuts,
        SUM(strikes)               AS strikes,
        SUM(strikesCalled)         AS strikesCalled,
        SUM(strikesPitchOuts)      AS strikesPitchOuts,
        SUM(missedBunts)           AS missedBunts,
        SUM(swingAndMissStrikes)   AS swingAndMissStrikes,
        SUM(swingsPitchOuts)       AS swingsPitchOuts,
        SUM(swings)                AS swings,
        SUM(swingsZeroAndZero)     AS swingsZeroAndZero,
        SUM(swingsZeroAndOne)      AS swingsZeroAndOne,
        SUM(swingsZeroAndTwo)      AS swingsZeroAndTwo,
        SUM(swingsOneAndZero)      AS swingsOneAndZero,
        SUM(swingsOneAndOne)       AS swingsOneAndOne,
        SUM(swingsOneAndTwo)       AS swingsOneAndTwo,
        SUM(swingsTwoAndZero)      AS swingsTwoAndZero,
        SUM(swingsTwoAndOne)       AS swingsTwoAndOne,
        SUM(swingsTwoAndTwo)       AS swingsTwoAndTwo,
        SUM(swingsThreeAndZero)    AS swingsThreeAndZero,
        SUM(swingsThreeAndOne)     AS swingsThreeAndOne,
        SUM(swingsThreeAndTwo)     AS swingsThreeAndTwo,
        SUM(flyBalls)              AS flyBalls,
        SUM(groundBalls)           AS groundBalls,
        SUM(lineDrives)            AS lineDrives,
        SUM(popUps)                AS popUps,
        SUM(groundBunts)           AS groundBunts,
        SUM(popupBunts)            AS popupBunts,
        SUM(lineDriveBunts)        AS lineDriveBunts,
        4186695649      AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2'  AS groupingDescription
FROM data
GROUP BY majorLeagueId, seasonId, gameType2;


-- ── Grouping 3215925615: MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID ──────────────────────────────────────────────
INSERT INTO agg_batting_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        venueId,
        officialId,
        opposingTeamId,
        atbats,
        balks,
        batterInterferences,
        bunts,
        catcherInterferences,
        doubles,
        fanInterferences,
        fieldErrors,
        fieldersChoice,
        flyouts,
        forceOuts,
        games,
        groundedIntoDoublePlays,
        groundedIntoTriplePlays,
        groundOuts,
        hitByPitch,
        hits,
        homeRuns,
        intentionalWalks,
        lineOuts,
        passedBalls,
        popOuts,
        runsBattedIn,
        sacBunts,
        sacFlies,
        singles,
        strikeOuts,
        triples,
        walks,
        wildPitches,
        balls,
        ballsPitchOut,
        ballsInDirt,
        intentBalls,
        fouls,
        foulBunts,
        foulTips,
        foulPitchOuts,
        hitIntoPlay,
        pitches,
        pitchOuts,
        strikes,
        strikesCalled,
        strikesPitchOuts,
        missedBunts,
        swingAndMissStrikes,
        swingsPitchOuts,
        swings,
        swingsZeroAndZero,
        swingsZeroAndOne,
        swingsZeroAndTwo,
        swingsOneAndZero,
        swingsOneAndOne,
        swingsOneAndTwo,
        swingsTwoAndZero,
        swingsTwoAndOne,
        swingsTwoAndTwo,
        swingsThreeAndZero,
        swingsThreeAndOne,
        swingsThreeAndTwo,
        flyBalls,
        groundBalls,
        lineDrives,
        popUps,
        groundBunts,
        popupBunts,
        lineDriveBunts,
        groupingId,
        groupingDescription
)
WITH bs AS (
    SELECT *, pitchingTeamId AS opposingTeamId
    FROM game_player_split_stats
),
g AS (
    SELECT majorLeagueId, seasonId, gamePk, gameType2, venueId, homeTeamId
    FROM games
    WHERE gameType2 IN ('PS', 'RS')
),
officials AS (
    SELECT gamePk, officialId
    FROM game_officials
    WHERE position = 'Home Plate'
),
data AS (
    SELECT
        g.majorLeagueId, g.seasonId, g.gamePk, g.gameType2, g.venueId,
        CASE WHEN g.homeTeamId = bs.battingTeamId THEN 'home' ELSE 'away' END AS teamType,
        bs.battingTeamId  AS teamId,
        bs.batterId       AS playerId,
        bs.opposingTeamId,
        o.officialId,
        batSide, pitchHand, menOnBase,
        (batterInterferences + bunts + doubles + fanInterferences + fieldErrors
         + fieldersChoice + flyouts + forceOuts + groundedIntoDoublePlays
         + triplePlays + groundOuts + homeRuns + lineOuts + popOuts
         + singles + strikeOuts + triples) AS atbats,
        balks, batterInterferences, bunts, catcherInterferences, doubles,
        fanInterferences, fieldErrors, fieldersChoice, flyouts, forceOuts,
        groundedIntoDoublePlays, groundOuts, hitByPitch, homeRuns,
        intentionalWalks, lineOuts, passedBalls, popOuts, runsBattedIn,
        sacBunts, sacFlies, singles, strikeOuts, triples, triplePlays,
        walks, wildPitches,
        balls, ballsPitchOut, ballsInDirt, intentBalls, fouls, foulBunts,
        foulTips, foulPitchOuts, hitIntoPlay, pitches, pitchOuts, strikes,
        strikesCalled, strikesPitchOuts, missedBunts, swingAndMissStrikes,
        swingsPitchOuts, swings,
        swingsZeroAndZero, swingsZeroAndOne, swingsZeroAndTwo,
        swingsOneAndZero,  swingsOneAndOne,  swingsOneAndTwo,
        swingsTwoAndZero,  swingsTwoAndOne,  swingsTwoAndTwo,
        swingsThreeAndZero,swingsThreeAndOne, swingsThreeAndTwo,
        flyBalls, groundBalls, lineDrives, popUps,
        groundBunts, popupBunts, lineDriveBunts
    FROM g
    INNER JOIN bs       ON g.gamePk = bs.gamePk
    LEFT  JOIN officials o ON g.gamePk = o.gamePk
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        NULL AS teamType,
        NULL AS playerId,
        NULL AS venueId,
        NULL AS officialId,
        NULL AS opposingTeamId,
        SUM(atbats)                AS atbats,
        SUM(balks)                 AS balks,
        SUM(batterInterferences)   AS batterInterferences,
        SUM(bunts)                 AS bunts,
        SUM(catcherInterferences)  AS catcherInterferences,
        SUM(doubles)               AS doubles,
        SUM(fanInterferences)      AS fanInterferences,
        SUM(fieldErrors)           AS fieldErrors,
        SUM(fieldersChoice)        AS fieldersChoice,
        SUM(flyouts)               AS flyouts,
        SUM(forceOuts)             AS forceOuts,
        COUNT(DISTINCT gamePk)     AS games,
        SUM(groundedIntoDoublePlays) AS groundedIntoDoublePlays,
        SUM(triplePlays)           AS groundedIntoTriplePlays,
        SUM(groundOuts)            AS groundOuts,
        SUM(hitByPitch)            AS hitByPitch,
        SUM(singles)+SUM(doubles)+SUM(triples)+SUM(homeRuns) AS hits,
        SUM(homeRuns)              AS homeRuns,
        SUM(intentionalWalks)      AS intentionalWalks,
        SUM(lineOuts)              AS lineOuts,
        SUM(passedBalls)           AS passedBalls,
        SUM(popOuts)               AS popOuts,
        SUM(runsBattedIn)          AS runsBattedIn,
        SUM(sacBunts)              AS sacBunts,
        SUM(sacFlies)              AS sacFlies,
        SUM(singles)               AS singles,
        SUM(strikeOuts)            AS strikeOuts,
        SUM(triples)               AS triples,
        SUM(walks)                 AS walks,
        SUM(wildPitches)           AS wildPitches,
        SUM(balls)                 AS balls,
        SUM(ballsPitchOut)         AS ballsPitchOut,
        SUM(ballsInDirt)           AS ballsInDirt,
        SUM(intentBalls)           AS intentBalls,
        SUM(fouls)                 AS fouls,
        SUM(foulBunts)             AS foulBunts,
        SUM(foulTips)              AS foulTips,
        SUM(foulPitchOuts)         AS foulPitchOuts,
        SUM(hitIntoPlay)           AS hitIntoPlay,
        SUM(pitches)               AS pitches,
        SUM(pitchOuts)             AS pitchOuts,
        SUM(strikes)               AS strikes,
        SUM(strikesCalled)         AS strikesCalled,
        SUM(strikesPitchOuts)      AS strikesPitchOuts,
        SUM(missedBunts)           AS missedBunts,
        SUM(swingAndMissStrikes)   AS swingAndMissStrikes,
        SUM(swingsPitchOuts)       AS swingsPitchOuts,
        SUM(swings)                AS swings,
        SUM(swingsZeroAndZero)     AS swingsZeroAndZero,
        SUM(swingsZeroAndOne)      AS swingsZeroAndOne,
        SUM(swingsZeroAndTwo)      AS swingsZeroAndTwo,
        SUM(swingsOneAndZero)      AS swingsOneAndZero,
        SUM(swingsOneAndOne)       AS swingsOneAndOne,
        SUM(swingsOneAndTwo)       AS swingsOneAndTwo,
        SUM(swingsTwoAndZero)      AS swingsTwoAndZero,
        SUM(swingsTwoAndOne)       AS swingsTwoAndOne,
        SUM(swingsTwoAndTwo)       AS swingsTwoAndTwo,
        SUM(swingsThreeAndZero)    AS swingsThreeAndZero,
        SUM(swingsThreeAndOne)     AS swingsThreeAndOne,
        SUM(swingsThreeAndTwo)     AS swingsThreeAndTwo,
        SUM(flyBalls)              AS flyBalls,
        SUM(groundBalls)           AS groundBalls,
        SUM(lineDrives)            AS lineDrives,
        SUM(popUps)                AS popUps,
        SUM(groundBunts)           AS groundBunts,
        SUM(popupBunts)            AS popupBunts,
        SUM(lineDriveBunts)        AS lineDriveBunts,
        3215925615      AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID'  AS groupingDescription
FROM data
GROUP BY majorLeagueId, seasonId, gameType2, teamId;


-- ── Grouping 1467325589: MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID_TEAMTYPE_PLAYERID ──────────────────────────────────────────────
INSERT INTO agg_batting_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        venueId,
        officialId,
        opposingTeamId,
        atbats,
        balks,
        batterInterferences,
        bunts,
        catcherInterferences,
        doubles,
        fanInterferences,
        fieldErrors,
        fieldersChoice,
        flyouts,
        forceOuts,
        games,
        groundedIntoDoublePlays,
        groundedIntoTriplePlays,
        groundOuts,
        hitByPitch,
        hits,
        homeRuns,
        intentionalWalks,
        lineOuts,
        passedBalls,
        popOuts,
        runsBattedIn,
        sacBunts,
        sacFlies,
        singles,
        strikeOuts,
        triples,
        walks,
        wildPitches,
        balls,
        ballsPitchOut,
        ballsInDirt,
        intentBalls,
        fouls,
        foulBunts,
        foulTips,
        foulPitchOuts,
        hitIntoPlay,
        pitches,
        pitchOuts,
        strikes,
        strikesCalled,
        strikesPitchOuts,
        missedBunts,
        swingAndMissStrikes,
        swingsPitchOuts,
        swings,
        swingsZeroAndZero,
        swingsZeroAndOne,
        swingsZeroAndTwo,
        swingsOneAndZero,
        swingsOneAndOne,
        swingsOneAndTwo,
        swingsTwoAndZero,
        swingsTwoAndOne,
        swingsTwoAndTwo,
        swingsThreeAndZero,
        swingsThreeAndOne,
        swingsThreeAndTwo,
        flyBalls,
        groundBalls,
        lineDrives,
        popUps,
        groundBunts,
        popupBunts,
        lineDriveBunts,
        groupingId,
        groupingDescription
)
WITH bs AS (
    SELECT *, pitchingTeamId AS opposingTeamId
    FROM game_player_split_stats
),
g AS (
    SELECT majorLeagueId, seasonId, gamePk, gameType2, venueId, homeTeamId
    FROM games
    WHERE gameType2 IN ('PS', 'RS')
),
officials AS (
    SELECT gamePk, officialId
    FROM game_officials
    WHERE position = 'Home Plate'
),
data AS (
    SELECT
        g.majorLeagueId, g.seasonId, g.gamePk, g.gameType2, g.venueId,
        CASE WHEN g.homeTeamId = bs.battingTeamId THEN 'home' ELSE 'away' END AS teamType,
        bs.battingTeamId  AS teamId,
        bs.batterId       AS playerId,
        bs.opposingTeamId,
        o.officialId,
        batSide, pitchHand, menOnBase,
        (batterInterferences + bunts + doubles + fanInterferences + fieldErrors
         + fieldersChoice + flyouts + forceOuts + groundedIntoDoublePlays
         + triplePlays + groundOuts + homeRuns + lineOuts + popOuts
         + singles + strikeOuts + triples) AS atbats,
        balks, batterInterferences, bunts, catcherInterferences, doubles,
        fanInterferences, fieldErrors, fieldersChoice, flyouts, forceOuts,
        groundedIntoDoublePlays, groundOuts, hitByPitch, homeRuns,
        intentionalWalks, lineOuts, passedBalls, popOuts, runsBattedIn,
        sacBunts, sacFlies, singles, strikeOuts, triples, triplePlays,
        walks, wildPitches,
        balls, ballsPitchOut, ballsInDirt, intentBalls, fouls, foulBunts,
        foulTips, foulPitchOuts, hitIntoPlay, pitches, pitchOuts, strikes,
        strikesCalled, strikesPitchOuts, missedBunts, swingAndMissStrikes,
        swingsPitchOuts, swings,
        swingsZeroAndZero, swingsZeroAndOne, swingsZeroAndTwo,
        swingsOneAndZero,  swingsOneAndOne,  swingsOneAndTwo,
        swingsTwoAndZero,  swingsTwoAndOne,  swingsTwoAndTwo,
        swingsThreeAndZero,swingsThreeAndOne, swingsThreeAndTwo,
        flyBalls, groundBalls, lineDrives, popUps,
        groundBunts, popupBunts, lineDriveBunts
    FROM g
    INNER JOIN bs       ON g.gamePk = bs.gamePk
    LEFT  JOIN officials o ON g.gamePk = o.gamePk
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        NULL AS venueId,
        NULL AS officialId,
        NULL AS opposingTeamId,
        SUM(atbats)                AS atbats,
        SUM(balks)                 AS balks,
        SUM(batterInterferences)   AS batterInterferences,
        SUM(bunts)                 AS bunts,
        SUM(catcherInterferences)  AS catcherInterferences,
        SUM(doubles)               AS doubles,
        SUM(fanInterferences)      AS fanInterferences,
        SUM(fieldErrors)           AS fieldErrors,
        SUM(fieldersChoice)        AS fieldersChoice,
        SUM(flyouts)               AS flyouts,
        SUM(forceOuts)             AS forceOuts,
        COUNT(DISTINCT gamePk)     AS games,
        SUM(groundedIntoDoublePlays) AS groundedIntoDoublePlays,
        SUM(triplePlays)           AS groundedIntoTriplePlays,
        SUM(groundOuts)            AS groundOuts,
        SUM(hitByPitch)            AS hitByPitch,
        SUM(singles)+SUM(doubles)+SUM(triples)+SUM(homeRuns) AS hits,
        SUM(homeRuns)              AS homeRuns,
        SUM(intentionalWalks)      AS intentionalWalks,
        SUM(lineOuts)              AS lineOuts,
        SUM(passedBalls)           AS passedBalls,
        SUM(popOuts)               AS popOuts,
        SUM(runsBattedIn)          AS runsBattedIn,
        SUM(sacBunts)              AS sacBunts,
        SUM(sacFlies)              AS sacFlies,
        SUM(singles)               AS singles,
        SUM(strikeOuts)            AS strikeOuts,
        SUM(triples)               AS triples,
        SUM(walks)                 AS walks,
        SUM(wildPitches)           AS wildPitches,
        SUM(balls)                 AS balls,
        SUM(ballsPitchOut)         AS ballsPitchOut,
        SUM(ballsInDirt)           AS ballsInDirt,
        SUM(intentBalls)           AS intentBalls,
        SUM(fouls)                 AS fouls,
        SUM(foulBunts)             AS foulBunts,
        SUM(foulTips)              AS foulTips,
        SUM(foulPitchOuts)         AS foulPitchOuts,
        SUM(hitIntoPlay)           AS hitIntoPlay,
        SUM(pitches)               AS pitches,
        SUM(pitchOuts)             AS pitchOuts,
        SUM(strikes)               AS strikes,
        SUM(strikesCalled)         AS strikesCalled,
        SUM(strikesPitchOuts)      AS strikesPitchOuts,
        SUM(missedBunts)           AS missedBunts,
        SUM(swingAndMissStrikes)   AS swingAndMissStrikes,
        SUM(swingsPitchOuts)       AS swingsPitchOuts,
        SUM(swings)                AS swings,
        SUM(swingsZeroAndZero)     AS swingsZeroAndZero,
        SUM(swingsZeroAndOne)      AS swingsZeroAndOne,
        SUM(swingsZeroAndTwo)      AS swingsZeroAndTwo,
        SUM(swingsOneAndZero)      AS swingsOneAndZero,
        SUM(swingsOneAndOne)       AS swingsOneAndOne,
        SUM(swingsOneAndTwo)       AS swingsOneAndTwo,
        SUM(swingsTwoAndZero)      AS swingsTwoAndZero,
        SUM(swingsTwoAndOne)       AS swingsTwoAndOne,
        SUM(swingsTwoAndTwo)       AS swingsTwoAndTwo,
        SUM(swingsThreeAndZero)    AS swingsThreeAndZero,
        SUM(swingsThreeAndOne)     AS swingsThreeAndOne,
        SUM(swingsThreeAndTwo)     AS swingsThreeAndTwo,
        SUM(flyBalls)              AS flyBalls,
        SUM(groundBalls)           AS groundBalls,
        SUM(lineDrives)            AS lineDrives,
        SUM(popUps)                AS popUps,
        SUM(groundBunts)           AS groundBunts,
        SUM(popupBunts)            AS popupBunts,
        SUM(lineDriveBunts)        AS lineDriveBunts,
        1467325589      AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID_TEAMTYPE_PLAYERID'  AS groupingDescription
FROM data
GROUP BY majorLeagueId, seasonId, gameType2, teamId, teamType, playerId;


-- ── Grouping 1730332978: MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID_TEAMTYPE ──────────────────────────────────────────────
INSERT INTO agg_batting_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        venueId,
        officialId,
        opposingTeamId,
        atbats,
        balks,
        batterInterferences,
        bunts,
        catcherInterferences,
        doubles,
        fanInterferences,
        fieldErrors,
        fieldersChoice,
        flyouts,
        forceOuts,
        games,
        groundedIntoDoublePlays,
        groundedIntoTriplePlays,
        groundOuts,
        hitByPitch,
        hits,
        homeRuns,
        intentionalWalks,
        lineOuts,
        passedBalls,
        popOuts,
        runsBattedIn,
        sacBunts,
        sacFlies,
        singles,
        strikeOuts,
        triples,
        walks,
        wildPitches,
        balls,
        ballsPitchOut,
        ballsInDirt,
        intentBalls,
        fouls,
        foulBunts,
        foulTips,
        foulPitchOuts,
        hitIntoPlay,
        pitches,
        pitchOuts,
        strikes,
        strikesCalled,
        strikesPitchOuts,
        missedBunts,
        swingAndMissStrikes,
        swingsPitchOuts,
        swings,
        swingsZeroAndZero,
        swingsZeroAndOne,
        swingsZeroAndTwo,
        swingsOneAndZero,
        swingsOneAndOne,
        swingsOneAndTwo,
        swingsTwoAndZero,
        swingsTwoAndOne,
        swingsTwoAndTwo,
        swingsThreeAndZero,
        swingsThreeAndOne,
        swingsThreeAndTwo,
        flyBalls,
        groundBalls,
        lineDrives,
        popUps,
        groundBunts,
        popupBunts,
        lineDriveBunts,
        groupingId,
        groupingDescription
)
WITH bs AS (
    SELECT *, pitchingTeamId AS opposingTeamId
    FROM game_player_split_stats
),
g AS (
    SELECT majorLeagueId, seasonId, gamePk, gameType2, venueId, homeTeamId
    FROM games
    WHERE gameType2 IN ('PS', 'RS')
),
officials AS (
    SELECT gamePk, officialId
    FROM game_officials
    WHERE position = 'Home Plate'
),
data AS (
    SELECT
        g.majorLeagueId, g.seasonId, g.gamePk, g.gameType2, g.venueId,
        CASE WHEN g.homeTeamId = bs.battingTeamId THEN 'home' ELSE 'away' END AS teamType,
        bs.battingTeamId  AS teamId,
        bs.batterId       AS playerId,
        bs.opposingTeamId,
        o.officialId,
        batSide, pitchHand, menOnBase,
        (batterInterferences + bunts + doubles + fanInterferences + fieldErrors
         + fieldersChoice + flyouts + forceOuts + groundedIntoDoublePlays
         + triplePlays + groundOuts + homeRuns + lineOuts + popOuts
         + singles + strikeOuts + triples) AS atbats,
        balks, batterInterferences, bunts, catcherInterferences, doubles,
        fanInterferences, fieldErrors, fieldersChoice, flyouts, forceOuts,
        groundedIntoDoublePlays, groundOuts, hitByPitch, homeRuns,
        intentionalWalks, lineOuts, passedBalls, popOuts, runsBattedIn,
        sacBunts, sacFlies, singles, strikeOuts, triples, triplePlays,
        walks, wildPitches,
        balls, ballsPitchOut, ballsInDirt, intentBalls, fouls, foulBunts,
        foulTips, foulPitchOuts, hitIntoPlay, pitches, pitchOuts, strikes,
        strikesCalled, strikesPitchOuts, missedBunts, swingAndMissStrikes,
        swingsPitchOuts, swings,
        swingsZeroAndZero, swingsZeroAndOne, swingsZeroAndTwo,
        swingsOneAndZero,  swingsOneAndOne,  swingsOneAndTwo,
        swingsTwoAndZero,  swingsTwoAndOne,  swingsTwoAndTwo,
        swingsThreeAndZero,swingsThreeAndOne, swingsThreeAndTwo,
        flyBalls, groundBalls, lineDrives, popUps,
        groundBunts, popupBunts, lineDriveBunts
    FROM g
    INNER JOIN bs       ON g.gamePk = bs.gamePk
    LEFT  JOIN officials o ON g.gamePk = o.gamePk
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        NULL AS playerId,
        NULL AS venueId,
        NULL AS officialId,
        NULL AS opposingTeamId,
        SUM(atbats)                AS atbats,
        SUM(balks)                 AS balks,
        SUM(batterInterferences)   AS batterInterferences,
        SUM(bunts)                 AS bunts,
        SUM(catcherInterferences)  AS catcherInterferences,
        SUM(doubles)               AS doubles,
        SUM(fanInterferences)      AS fanInterferences,
        SUM(fieldErrors)           AS fieldErrors,
        SUM(fieldersChoice)        AS fieldersChoice,
        SUM(flyouts)               AS flyouts,
        SUM(forceOuts)             AS forceOuts,
        COUNT(DISTINCT gamePk)     AS games,
        SUM(groundedIntoDoublePlays) AS groundedIntoDoublePlays,
        SUM(triplePlays)           AS groundedIntoTriplePlays,
        SUM(groundOuts)            AS groundOuts,
        SUM(hitByPitch)            AS hitByPitch,
        SUM(singles)+SUM(doubles)+SUM(triples)+SUM(homeRuns) AS hits,
        SUM(homeRuns)              AS homeRuns,
        SUM(intentionalWalks)      AS intentionalWalks,
        SUM(lineOuts)              AS lineOuts,
        SUM(passedBalls)           AS passedBalls,
        SUM(popOuts)               AS popOuts,
        SUM(runsBattedIn)          AS runsBattedIn,
        SUM(sacBunts)              AS sacBunts,
        SUM(sacFlies)              AS sacFlies,
        SUM(singles)               AS singles,
        SUM(strikeOuts)            AS strikeOuts,
        SUM(triples)               AS triples,
        SUM(walks)                 AS walks,
        SUM(wildPitches)           AS wildPitches,
        SUM(balls)                 AS balls,
        SUM(ballsPitchOut)         AS ballsPitchOut,
        SUM(ballsInDirt)           AS ballsInDirt,
        SUM(intentBalls)           AS intentBalls,
        SUM(fouls)                 AS fouls,
        SUM(foulBunts)             AS foulBunts,
        SUM(foulTips)              AS foulTips,
        SUM(foulPitchOuts)         AS foulPitchOuts,
        SUM(hitIntoPlay)           AS hitIntoPlay,
        SUM(pitches)               AS pitches,
        SUM(pitchOuts)             AS pitchOuts,
        SUM(strikes)               AS strikes,
        SUM(strikesCalled)         AS strikesCalled,
        SUM(strikesPitchOuts)      AS strikesPitchOuts,
        SUM(missedBunts)           AS missedBunts,
        SUM(swingAndMissStrikes)   AS swingAndMissStrikes,
        SUM(swingsPitchOuts)       AS swingsPitchOuts,
        SUM(swings)                AS swings,
        SUM(swingsZeroAndZero)     AS swingsZeroAndZero,
        SUM(swingsZeroAndOne)      AS swingsZeroAndOne,
        SUM(swingsZeroAndTwo)      AS swingsZeroAndTwo,
        SUM(swingsOneAndZero)      AS swingsOneAndZero,
        SUM(swingsOneAndOne)       AS swingsOneAndOne,
        SUM(swingsOneAndTwo)       AS swingsOneAndTwo,
        SUM(swingsTwoAndZero)      AS swingsTwoAndZero,
        SUM(swingsTwoAndOne)       AS swingsTwoAndOne,
        SUM(swingsTwoAndTwo)       AS swingsTwoAndTwo,
        SUM(swingsThreeAndZero)    AS swingsThreeAndZero,
        SUM(swingsThreeAndOne)     AS swingsThreeAndOne,
        SUM(swingsThreeAndTwo)     AS swingsThreeAndTwo,
        SUM(flyBalls)              AS flyBalls,
        SUM(groundBalls)           AS groundBalls,
        SUM(lineDrives)            AS lineDrives,
        SUM(popUps)                AS popUps,
        SUM(groundBunts)           AS groundBunts,
        SUM(popupBunts)            AS popupBunts,
        SUM(lineDriveBunts)        AS lineDriveBunts,
        1730332978      AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID_TEAMTYPE'  AS groupingDescription
FROM data
GROUP BY majorLeagueId, seasonId, gameType2, teamId, teamType;


-- ── Grouping 2723138969: MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID_PLAYERID ──────────────────────────────────────────────
INSERT INTO agg_batting_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        venueId,
        officialId,
        opposingTeamId,
        atbats,
        balks,
        batterInterferences,
        bunts,
        catcherInterferences,
        doubles,
        fanInterferences,
        fieldErrors,
        fieldersChoice,
        flyouts,
        forceOuts,
        games,
        groundedIntoDoublePlays,
        groundedIntoTriplePlays,
        groundOuts,
        hitByPitch,
        hits,
        homeRuns,
        intentionalWalks,
        lineOuts,
        passedBalls,
        popOuts,
        runsBattedIn,
        sacBunts,
        sacFlies,
        singles,
        strikeOuts,
        triples,
        walks,
        wildPitches,
        balls,
        ballsPitchOut,
        ballsInDirt,
        intentBalls,
        fouls,
        foulBunts,
        foulTips,
        foulPitchOuts,
        hitIntoPlay,
        pitches,
        pitchOuts,
        strikes,
        strikesCalled,
        strikesPitchOuts,
        missedBunts,
        swingAndMissStrikes,
        swingsPitchOuts,
        swings,
        swingsZeroAndZero,
        swingsZeroAndOne,
        swingsZeroAndTwo,
        swingsOneAndZero,
        swingsOneAndOne,
        swingsOneAndTwo,
        swingsTwoAndZero,
        swingsTwoAndOne,
        swingsTwoAndTwo,
        swingsThreeAndZero,
        swingsThreeAndOne,
        swingsThreeAndTwo,
        flyBalls,
        groundBalls,
        lineDrives,
        popUps,
        groundBunts,
        popupBunts,
        lineDriveBunts,
        groupingId,
        groupingDescription
)
WITH bs AS (
    SELECT *, pitchingTeamId AS opposingTeamId
    FROM game_player_split_stats
),
g AS (
    SELECT majorLeagueId, seasonId, gamePk, gameType2, venueId, homeTeamId
    FROM games
    WHERE gameType2 IN ('PS', 'RS')
),
officials AS (
    SELECT gamePk, officialId
    FROM game_officials
    WHERE position = 'Home Plate'
),
data AS (
    SELECT
        g.majorLeagueId, g.seasonId, g.gamePk, g.gameType2, g.venueId,
        CASE WHEN g.homeTeamId = bs.battingTeamId THEN 'home' ELSE 'away' END AS teamType,
        bs.battingTeamId  AS teamId,
        bs.batterId       AS playerId,
        bs.opposingTeamId,
        o.officialId,
        batSide, pitchHand, menOnBase,
        (batterInterferences + bunts + doubles + fanInterferences + fieldErrors
         + fieldersChoice + flyouts + forceOuts + groundedIntoDoublePlays
         + triplePlays + groundOuts + homeRuns + lineOuts + popOuts
         + singles + strikeOuts + triples) AS atbats,
        balks, batterInterferences, bunts, catcherInterferences, doubles,
        fanInterferences, fieldErrors, fieldersChoice, flyouts, forceOuts,
        groundedIntoDoublePlays, groundOuts, hitByPitch, homeRuns,
        intentionalWalks, lineOuts, passedBalls, popOuts, runsBattedIn,
        sacBunts, sacFlies, singles, strikeOuts, triples, triplePlays,
        walks, wildPitches,
        balls, ballsPitchOut, ballsInDirt, intentBalls, fouls, foulBunts,
        foulTips, foulPitchOuts, hitIntoPlay, pitches, pitchOuts, strikes,
        strikesCalled, strikesPitchOuts, missedBunts, swingAndMissStrikes,
        swingsPitchOuts, swings,
        swingsZeroAndZero, swingsZeroAndOne, swingsZeroAndTwo,
        swingsOneAndZero,  swingsOneAndOne,  swingsOneAndTwo,
        swingsTwoAndZero,  swingsTwoAndOne,  swingsTwoAndTwo,
        swingsThreeAndZero,swingsThreeAndOne, swingsThreeAndTwo,
        flyBalls, groundBalls, lineDrives, popUps,
        groundBunts, popupBunts, lineDriveBunts
    FROM g
    INNER JOIN bs       ON g.gamePk = bs.gamePk
    LEFT  JOIN officials o ON g.gamePk = o.gamePk
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        NULL AS teamType,
        playerId,
        NULL AS venueId,
        NULL AS officialId,
        NULL AS opposingTeamId,
        SUM(atbats)                AS atbats,
        SUM(balks)                 AS balks,
        SUM(batterInterferences)   AS batterInterferences,
        SUM(bunts)                 AS bunts,
        SUM(catcherInterferences)  AS catcherInterferences,
        SUM(doubles)               AS doubles,
        SUM(fanInterferences)      AS fanInterferences,
        SUM(fieldErrors)           AS fieldErrors,
        SUM(fieldersChoice)        AS fieldersChoice,
        SUM(flyouts)               AS flyouts,
        SUM(forceOuts)             AS forceOuts,
        COUNT(DISTINCT gamePk)     AS games,
        SUM(groundedIntoDoublePlays) AS groundedIntoDoublePlays,
        SUM(triplePlays)           AS groundedIntoTriplePlays,
        SUM(groundOuts)            AS groundOuts,
        SUM(hitByPitch)            AS hitByPitch,
        SUM(singles)+SUM(doubles)+SUM(triples)+SUM(homeRuns) AS hits,
        SUM(homeRuns)              AS homeRuns,
        SUM(intentionalWalks)      AS intentionalWalks,
        SUM(lineOuts)              AS lineOuts,
        SUM(passedBalls)           AS passedBalls,
        SUM(popOuts)               AS popOuts,
        SUM(runsBattedIn)          AS runsBattedIn,
        SUM(sacBunts)              AS sacBunts,
        SUM(sacFlies)              AS sacFlies,
        SUM(singles)               AS singles,
        SUM(strikeOuts)            AS strikeOuts,
        SUM(triples)               AS triples,
        SUM(walks)                 AS walks,
        SUM(wildPitches)           AS wildPitches,
        SUM(balls)                 AS balls,
        SUM(ballsPitchOut)         AS ballsPitchOut,
        SUM(ballsInDirt)           AS ballsInDirt,
        SUM(intentBalls)           AS intentBalls,
        SUM(fouls)                 AS fouls,
        SUM(foulBunts)             AS foulBunts,
        SUM(foulTips)              AS foulTips,
        SUM(foulPitchOuts)         AS foulPitchOuts,
        SUM(hitIntoPlay)           AS hitIntoPlay,
        SUM(pitches)               AS pitches,
        SUM(pitchOuts)             AS pitchOuts,
        SUM(strikes)               AS strikes,
        SUM(strikesCalled)         AS strikesCalled,
        SUM(strikesPitchOuts)      AS strikesPitchOuts,
        SUM(missedBunts)           AS missedBunts,
        SUM(swingAndMissStrikes)   AS swingAndMissStrikes,
        SUM(swingsPitchOuts)       AS swingsPitchOuts,
        SUM(swings)                AS swings,
        SUM(swingsZeroAndZero)     AS swingsZeroAndZero,
        SUM(swingsZeroAndOne)      AS swingsZeroAndOne,
        SUM(swingsZeroAndTwo)      AS swingsZeroAndTwo,
        SUM(swingsOneAndZero)      AS swingsOneAndZero,
        SUM(swingsOneAndOne)       AS swingsOneAndOne,
        SUM(swingsOneAndTwo)       AS swingsOneAndTwo,
        SUM(swingsTwoAndZero)      AS swingsTwoAndZero,
        SUM(swingsTwoAndOne)       AS swingsTwoAndOne,
        SUM(swingsTwoAndTwo)       AS swingsTwoAndTwo,
        SUM(swingsThreeAndZero)    AS swingsThreeAndZero,
        SUM(swingsThreeAndOne)     AS swingsThreeAndOne,
        SUM(swingsThreeAndTwo)     AS swingsThreeAndTwo,
        SUM(flyBalls)              AS flyBalls,
        SUM(groundBalls)           AS groundBalls,
        SUM(lineDrives)            AS lineDrives,
        SUM(popUps)                AS popUps,
        SUM(groundBunts)           AS groundBunts,
        SUM(popupBunts)            AS popupBunts,
        SUM(lineDriveBunts)        AS lineDriveBunts,
        2723138969      AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID_PLAYERID'  AS groupingDescription
FROM data
GROUP BY majorLeagueId, seasonId, gameType2, teamId, playerId;


-- ── Grouping 3213375551: MAJORLEAGUEID_SEASONID_GAMETYPE2_VENUEID ──────────────────────────────────────────────
INSERT INTO agg_batting_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        venueId,
        officialId,
        opposingTeamId,
        atbats,
        balks,
        batterInterferences,
        bunts,
        catcherInterferences,
        doubles,
        fanInterferences,
        fieldErrors,
        fieldersChoice,
        flyouts,
        forceOuts,
        games,
        groundedIntoDoublePlays,
        groundedIntoTriplePlays,
        groundOuts,
        hitByPitch,
        hits,
        homeRuns,
        intentionalWalks,
        lineOuts,
        passedBalls,
        popOuts,
        runsBattedIn,
        sacBunts,
        sacFlies,
        singles,
        strikeOuts,
        triples,
        walks,
        wildPitches,
        balls,
        ballsPitchOut,
        ballsInDirt,
        intentBalls,
        fouls,
        foulBunts,
        foulTips,
        foulPitchOuts,
        hitIntoPlay,
        pitches,
        pitchOuts,
        strikes,
        strikesCalled,
        strikesPitchOuts,
        missedBunts,
        swingAndMissStrikes,
        swingsPitchOuts,
        swings,
        swingsZeroAndZero,
        swingsZeroAndOne,
        swingsZeroAndTwo,
        swingsOneAndZero,
        swingsOneAndOne,
        swingsOneAndTwo,
        swingsTwoAndZero,
        swingsTwoAndOne,
        swingsTwoAndTwo,
        swingsThreeAndZero,
        swingsThreeAndOne,
        swingsThreeAndTwo,
        flyBalls,
        groundBalls,
        lineDrives,
        popUps,
        groundBunts,
        popupBunts,
        lineDriveBunts,
        groupingId,
        groupingDescription
)
WITH bs AS (
    SELECT *, pitchingTeamId AS opposingTeamId
    FROM game_player_split_stats
),
g AS (
    SELECT majorLeagueId, seasonId, gamePk, gameType2, venueId, homeTeamId
    FROM games
    WHERE gameType2 IN ('PS', 'RS')
),
officials AS (
    SELECT gamePk, officialId
    FROM game_officials
    WHERE position = 'Home Plate'
),
data AS (
    SELECT
        g.majorLeagueId, g.seasonId, g.gamePk, g.gameType2, g.venueId,
        CASE WHEN g.homeTeamId = bs.battingTeamId THEN 'home' ELSE 'away' END AS teamType,
        bs.battingTeamId  AS teamId,
        bs.batterId       AS playerId,
        bs.opposingTeamId,
        o.officialId,
        batSide, pitchHand, menOnBase,
        (batterInterferences + bunts + doubles + fanInterferences + fieldErrors
         + fieldersChoice + flyouts + forceOuts + groundedIntoDoublePlays
         + triplePlays + groundOuts + homeRuns + lineOuts + popOuts
         + singles + strikeOuts + triples) AS atbats,
        balks, batterInterferences, bunts, catcherInterferences, doubles,
        fanInterferences, fieldErrors, fieldersChoice, flyouts, forceOuts,
        groundedIntoDoublePlays, groundOuts, hitByPitch, homeRuns,
        intentionalWalks, lineOuts, passedBalls, popOuts, runsBattedIn,
        sacBunts, sacFlies, singles, strikeOuts, triples, triplePlays,
        walks, wildPitches,
        balls, ballsPitchOut, ballsInDirt, intentBalls, fouls, foulBunts,
        foulTips, foulPitchOuts, hitIntoPlay, pitches, pitchOuts, strikes,
        strikesCalled, strikesPitchOuts, missedBunts, swingAndMissStrikes,
        swingsPitchOuts, swings,
        swingsZeroAndZero, swingsZeroAndOne, swingsZeroAndTwo,
        swingsOneAndZero,  swingsOneAndOne,  swingsOneAndTwo,
        swingsTwoAndZero,  swingsTwoAndOne,  swingsTwoAndTwo,
        swingsThreeAndZero,swingsThreeAndOne, swingsThreeAndTwo,
        flyBalls, groundBalls, lineDrives, popUps,
        groundBunts, popupBunts, lineDriveBunts
    FROM g
    INNER JOIN bs       ON g.gamePk = bs.gamePk
    LEFT  JOIN officials o ON g.gamePk = o.gamePk
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        NULL AS teamId,
        NULL AS teamType,
        NULL AS playerId,
        venueId,
        NULL AS officialId,
        NULL AS opposingTeamId,
        SUM(atbats)                AS atbats,
        SUM(balks)                 AS balks,
        SUM(batterInterferences)   AS batterInterferences,
        SUM(bunts)                 AS bunts,
        SUM(catcherInterferences)  AS catcherInterferences,
        SUM(doubles)               AS doubles,
        SUM(fanInterferences)      AS fanInterferences,
        SUM(fieldErrors)           AS fieldErrors,
        SUM(fieldersChoice)        AS fieldersChoice,
        SUM(flyouts)               AS flyouts,
        SUM(forceOuts)             AS forceOuts,
        COUNT(DISTINCT gamePk)     AS games,
        SUM(groundedIntoDoublePlays) AS groundedIntoDoublePlays,
        SUM(triplePlays)           AS groundedIntoTriplePlays,
        SUM(groundOuts)            AS groundOuts,
        SUM(hitByPitch)            AS hitByPitch,
        SUM(singles)+SUM(doubles)+SUM(triples)+SUM(homeRuns) AS hits,
        SUM(homeRuns)              AS homeRuns,
        SUM(intentionalWalks)      AS intentionalWalks,
        SUM(lineOuts)              AS lineOuts,
        SUM(passedBalls)           AS passedBalls,
        SUM(popOuts)               AS popOuts,
        SUM(runsBattedIn)          AS runsBattedIn,
        SUM(sacBunts)              AS sacBunts,
        SUM(sacFlies)              AS sacFlies,
        SUM(singles)               AS singles,
        SUM(strikeOuts)            AS strikeOuts,
        SUM(triples)               AS triples,
        SUM(walks)                 AS walks,
        SUM(wildPitches)           AS wildPitches,
        SUM(balls)                 AS balls,
        SUM(ballsPitchOut)         AS ballsPitchOut,
        SUM(ballsInDirt)           AS ballsInDirt,
        SUM(intentBalls)           AS intentBalls,
        SUM(fouls)                 AS fouls,
        SUM(foulBunts)             AS foulBunts,
        SUM(foulTips)              AS foulTips,
        SUM(foulPitchOuts)         AS foulPitchOuts,
        SUM(hitIntoPlay)           AS hitIntoPlay,
        SUM(pitches)               AS pitches,
        SUM(pitchOuts)             AS pitchOuts,
        SUM(strikes)               AS strikes,
        SUM(strikesCalled)         AS strikesCalled,
        SUM(strikesPitchOuts)      AS strikesPitchOuts,
        SUM(missedBunts)           AS missedBunts,
        SUM(swingAndMissStrikes)   AS swingAndMissStrikes,
        SUM(swingsPitchOuts)       AS swingsPitchOuts,
        SUM(swings)                AS swings,
        SUM(swingsZeroAndZero)     AS swingsZeroAndZero,
        SUM(swingsZeroAndOne)      AS swingsZeroAndOne,
        SUM(swingsZeroAndTwo)      AS swingsZeroAndTwo,
        SUM(swingsOneAndZero)      AS swingsOneAndZero,
        SUM(swingsOneAndOne)       AS swingsOneAndOne,
        SUM(swingsOneAndTwo)       AS swingsOneAndTwo,
        SUM(swingsTwoAndZero)      AS swingsTwoAndZero,
        SUM(swingsTwoAndOne)       AS swingsTwoAndOne,
        SUM(swingsTwoAndTwo)       AS swingsTwoAndTwo,
        SUM(swingsThreeAndZero)    AS swingsThreeAndZero,
        SUM(swingsThreeAndOne)     AS swingsThreeAndOne,
        SUM(swingsThreeAndTwo)     AS swingsThreeAndTwo,
        SUM(flyBalls)              AS flyBalls,
        SUM(groundBalls)           AS groundBalls,
        SUM(lineDrives)            AS lineDrives,
        SUM(popUps)                AS popUps,
        SUM(groundBunts)           AS groundBunts,
        SUM(popupBunts)            AS popupBunts,
        SUM(lineDriveBunts)        AS lineDriveBunts,
        3213375551      AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_VENUEID'  AS groupingDescription
FROM data
GROUP BY majorLeagueId, seasonId, gameType2, venueId;


-- ── Grouping 2758182884: MAJORLEAGUEID_SEASONID_GAMETYPE2_PLAYERID ──────────────────────────────────────────────
INSERT INTO agg_batting_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        venueId,
        officialId,
        opposingTeamId,
        atbats,
        balks,
        batterInterferences,
        bunts,
        catcherInterferences,
        doubles,
        fanInterferences,
        fieldErrors,
        fieldersChoice,
        flyouts,
        forceOuts,
        games,
        groundedIntoDoublePlays,
        groundedIntoTriplePlays,
        groundOuts,
        hitByPitch,
        hits,
        homeRuns,
        intentionalWalks,
        lineOuts,
        passedBalls,
        popOuts,
        runsBattedIn,
        sacBunts,
        sacFlies,
        singles,
        strikeOuts,
        triples,
        walks,
        wildPitches,
        balls,
        ballsPitchOut,
        ballsInDirt,
        intentBalls,
        fouls,
        foulBunts,
        foulTips,
        foulPitchOuts,
        hitIntoPlay,
        pitches,
        pitchOuts,
        strikes,
        strikesCalled,
        strikesPitchOuts,
        missedBunts,
        swingAndMissStrikes,
        swingsPitchOuts,
        swings,
        swingsZeroAndZero,
        swingsZeroAndOne,
        swingsZeroAndTwo,
        swingsOneAndZero,
        swingsOneAndOne,
        swingsOneAndTwo,
        swingsTwoAndZero,
        swingsTwoAndOne,
        swingsTwoAndTwo,
        swingsThreeAndZero,
        swingsThreeAndOne,
        swingsThreeAndTwo,
        flyBalls,
        groundBalls,
        lineDrives,
        popUps,
        groundBunts,
        popupBunts,
        lineDriveBunts,
        groupingId,
        groupingDescription
)
WITH bs AS (
    SELECT *, pitchingTeamId AS opposingTeamId
    FROM game_player_split_stats
),
g AS (
    SELECT majorLeagueId, seasonId, gamePk, gameType2, venueId, homeTeamId
    FROM games
    WHERE gameType2 IN ('PS', 'RS')
),
officials AS (
    SELECT gamePk, officialId
    FROM game_officials
    WHERE position = 'Home Plate'
),
data AS (
    SELECT
        g.majorLeagueId, g.seasonId, g.gamePk, g.gameType2, g.venueId,
        CASE WHEN g.homeTeamId = bs.battingTeamId THEN 'home' ELSE 'away' END AS teamType,
        bs.battingTeamId  AS teamId,
        bs.batterId       AS playerId,
        bs.opposingTeamId,
        o.officialId,
        batSide, pitchHand, menOnBase,
        (batterInterferences + bunts + doubles + fanInterferences + fieldErrors
         + fieldersChoice + flyouts + forceOuts + groundedIntoDoublePlays
         + triplePlays + groundOuts + homeRuns + lineOuts + popOuts
         + singles + strikeOuts + triples) AS atbats,
        balks, batterInterferences, bunts, catcherInterferences, doubles,
        fanInterferences, fieldErrors, fieldersChoice, flyouts, forceOuts,
        groundedIntoDoublePlays, groundOuts, hitByPitch, homeRuns,
        intentionalWalks, lineOuts, passedBalls, popOuts, runsBattedIn,
        sacBunts, sacFlies, singles, strikeOuts, triples, triplePlays,
        walks, wildPitches,
        balls, ballsPitchOut, ballsInDirt, intentBalls, fouls, foulBunts,
        foulTips, foulPitchOuts, hitIntoPlay, pitches, pitchOuts, strikes,
        strikesCalled, strikesPitchOuts, missedBunts, swingAndMissStrikes,
        swingsPitchOuts, swings,
        swingsZeroAndZero, swingsZeroAndOne, swingsZeroAndTwo,
        swingsOneAndZero,  swingsOneAndOne,  swingsOneAndTwo,
        swingsTwoAndZero,  swingsTwoAndOne,  swingsTwoAndTwo,
        swingsThreeAndZero,swingsThreeAndOne, swingsThreeAndTwo,
        flyBalls, groundBalls, lineDrives, popUps,
        groundBunts, popupBunts, lineDriveBunts
    FROM g
    INNER JOIN bs       ON g.gamePk = bs.gamePk
    LEFT  JOIN officials o ON g.gamePk = o.gamePk
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        NULL AS teamId,
        NULL AS teamType,
        playerId,
        NULL AS venueId,
        NULL AS officialId,
        NULL AS opposingTeamId,
        SUM(atbats)                AS atbats,
        SUM(balks)                 AS balks,
        SUM(batterInterferences)   AS batterInterferences,
        SUM(bunts)                 AS bunts,
        SUM(catcherInterferences)  AS catcherInterferences,
        SUM(doubles)               AS doubles,
        SUM(fanInterferences)      AS fanInterferences,
        SUM(fieldErrors)           AS fieldErrors,
        SUM(fieldersChoice)        AS fieldersChoice,
        SUM(flyouts)               AS flyouts,
        SUM(forceOuts)             AS forceOuts,
        COUNT(DISTINCT gamePk)     AS games,
        SUM(groundedIntoDoublePlays) AS groundedIntoDoublePlays,
        SUM(triplePlays)           AS groundedIntoTriplePlays,
        SUM(groundOuts)            AS groundOuts,
        SUM(hitByPitch)            AS hitByPitch,
        SUM(singles)+SUM(doubles)+SUM(triples)+SUM(homeRuns) AS hits,
        SUM(homeRuns)              AS homeRuns,
        SUM(intentionalWalks)      AS intentionalWalks,
        SUM(lineOuts)              AS lineOuts,
        SUM(passedBalls)           AS passedBalls,
        SUM(popOuts)               AS popOuts,
        SUM(runsBattedIn)          AS runsBattedIn,
        SUM(sacBunts)              AS sacBunts,
        SUM(sacFlies)              AS sacFlies,
        SUM(singles)               AS singles,
        SUM(strikeOuts)            AS strikeOuts,
        SUM(triples)               AS triples,
        SUM(walks)                 AS walks,
        SUM(wildPitches)           AS wildPitches,
        SUM(balls)                 AS balls,
        SUM(ballsPitchOut)         AS ballsPitchOut,
        SUM(ballsInDirt)           AS ballsInDirt,
        SUM(intentBalls)           AS intentBalls,
        SUM(fouls)                 AS fouls,
        SUM(foulBunts)             AS foulBunts,
        SUM(foulTips)              AS foulTips,
        SUM(foulPitchOuts)         AS foulPitchOuts,
        SUM(hitIntoPlay)           AS hitIntoPlay,
        SUM(pitches)               AS pitches,
        SUM(pitchOuts)             AS pitchOuts,
        SUM(strikes)               AS strikes,
        SUM(strikesCalled)         AS strikesCalled,
        SUM(strikesPitchOuts)      AS strikesPitchOuts,
        SUM(missedBunts)           AS missedBunts,
        SUM(swingAndMissStrikes)   AS swingAndMissStrikes,
        SUM(swingsPitchOuts)       AS swingsPitchOuts,
        SUM(swings)                AS swings,
        SUM(swingsZeroAndZero)     AS swingsZeroAndZero,
        SUM(swingsZeroAndOne)      AS swingsZeroAndOne,
        SUM(swingsZeroAndTwo)      AS swingsZeroAndTwo,
        SUM(swingsOneAndZero)      AS swingsOneAndZero,
        SUM(swingsOneAndOne)       AS swingsOneAndOne,
        SUM(swingsOneAndTwo)       AS swingsOneAndTwo,
        SUM(swingsTwoAndZero)      AS swingsTwoAndZero,
        SUM(swingsTwoAndOne)       AS swingsTwoAndOne,
        SUM(swingsTwoAndTwo)       AS swingsTwoAndTwo,
        SUM(swingsThreeAndZero)    AS swingsThreeAndZero,
        SUM(swingsThreeAndOne)     AS swingsThreeAndOne,
        SUM(swingsThreeAndTwo)     AS swingsThreeAndTwo,
        SUM(flyBalls)              AS flyBalls,
        SUM(groundBalls)           AS groundBalls,
        SUM(lineDrives)            AS lineDrives,
        SUM(popUps)                AS popUps,
        SUM(groundBunts)           AS groundBunts,
        SUM(popupBunts)            AS popupBunts,
        SUM(lineDriveBunts)        AS lineDriveBunts,
        2758182884      AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_PLAYERID'  AS groupingDescription
FROM data
GROUP BY majorLeagueId, seasonId, gameType2, playerId;


-- ── Grouping 169487603: MAJORLEAGUEID_SEASONID_GAMETYPE2_VENUEID_TEAMID_TEAMTYPE ──────────────────────────────────────────────
INSERT INTO agg_batting_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        venueId,
        officialId,
        opposingTeamId,
        atbats,
        balks,
        batterInterferences,
        bunts,
        catcherInterferences,
        doubles,
        fanInterferences,
        fieldErrors,
        fieldersChoice,
        flyouts,
        forceOuts,
        games,
        groundedIntoDoublePlays,
        groundedIntoTriplePlays,
        groundOuts,
        hitByPitch,
        hits,
        homeRuns,
        intentionalWalks,
        lineOuts,
        passedBalls,
        popOuts,
        runsBattedIn,
        sacBunts,
        sacFlies,
        singles,
        strikeOuts,
        triples,
        walks,
        wildPitches,
        balls,
        ballsPitchOut,
        ballsInDirt,
        intentBalls,
        fouls,
        foulBunts,
        foulTips,
        foulPitchOuts,
        hitIntoPlay,
        pitches,
        pitchOuts,
        strikes,
        strikesCalled,
        strikesPitchOuts,
        missedBunts,
        swingAndMissStrikes,
        swingsPitchOuts,
        swings,
        swingsZeroAndZero,
        swingsZeroAndOne,
        swingsZeroAndTwo,
        swingsOneAndZero,
        swingsOneAndOne,
        swingsOneAndTwo,
        swingsTwoAndZero,
        swingsTwoAndOne,
        swingsTwoAndTwo,
        swingsThreeAndZero,
        swingsThreeAndOne,
        swingsThreeAndTwo,
        flyBalls,
        groundBalls,
        lineDrives,
        popUps,
        groundBunts,
        popupBunts,
        lineDriveBunts,
        groupingId,
        groupingDescription
)
WITH bs AS (
    SELECT *, pitchingTeamId AS opposingTeamId
    FROM game_player_split_stats
),
g AS (
    SELECT majorLeagueId, seasonId, gamePk, gameType2, venueId, homeTeamId
    FROM games
    WHERE gameType2 IN ('PS', 'RS')
),
officials AS (
    SELECT gamePk, officialId
    FROM game_officials
    WHERE position = 'Home Plate'
),
data AS (
    SELECT
        g.majorLeagueId, g.seasonId, g.gamePk, g.gameType2, g.venueId,
        CASE WHEN g.homeTeamId = bs.battingTeamId THEN 'home' ELSE 'away' END AS teamType,
        bs.battingTeamId  AS teamId,
        bs.batterId       AS playerId,
        bs.opposingTeamId,
        o.officialId,
        batSide, pitchHand, menOnBase,
        (batterInterferences + bunts + doubles + fanInterferences + fieldErrors
         + fieldersChoice + flyouts + forceOuts + groundedIntoDoublePlays
         + triplePlays + groundOuts + homeRuns + lineOuts + popOuts
         + singles + strikeOuts + triples) AS atbats,
        balks, batterInterferences, bunts, catcherInterferences, doubles,
        fanInterferences, fieldErrors, fieldersChoice, flyouts, forceOuts,
        groundedIntoDoublePlays, groundOuts, hitByPitch, homeRuns,
        intentionalWalks, lineOuts, passedBalls, popOuts, runsBattedIn,
        sacBunts, sacFlies, singles, strikeOuts, triples, triplePlays,
        walks, wildPitches,
        balls, ballsPitchOut, ballsInDirt, intentBalls, fouls, foulBunts,
        foulTips, foulPitchOuts, hitIntoPlay, pitches, pitchOuts, strikes,
        strikesCalled, strikesPitchOuts, missedBunts, swingAndMissStrikes,
        swingsPitchOuts, swings,
        swingsZeroAndZero, swingsZeroAndOne, swingsZeroAndTwo,
        swingsOneAndZero,  swingsOneAndOne,  swingsOneAndTwo,
        swingsTwoAndZero,  swingsTwoAndOne,  swingsTwoAndTwo,
        swingsThreeAndZero,swingsThreeAndOne, swingsThreeAndTwo,
        flyBalls, groundBalls, lineDrives, popUps,
        groundBunts, popupBunts, lineDriveBunts
    FROM g
    INNER JOIN bs       ON g.gamePk = bs.gamePk
    LEFT  JOIN officials o ON g.gamePk = o.gamePk
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        NULL AS playerId,
        venueId,
        NULL AS officialId,
        NULL AS opposingTeamId,
        SUM(atbats)                AS atbats,
        SUM(balks)                 AS balks,
        SUM(batterInterferences)   AS batterInterferences,
        SUM(bunts)                 AS bunts,
        SUM(catcherInterferences)  AS catcherInterferences,
        SUM(doubles)               AS doubles,
        SUM(fanInterferences)      AS fanInterferences,
        SUM(fieldErrors)           AS fieldErrors,
        SUM(fieldersChoice)        AS fieldersChoice,
        SUM(flyouts)               AS flyouts,
        SUM(forceOuts)             AS forceOuts,
        COUNT(DISTINCT gamePk)     AS games,
        SUM(groundedIntoDoublePlays) AS groundedIntoDoublePlays,
        SUM(triplePlays)           AS groundedIntoTriplePlays,
        SUM(groundOuts)            AS groundOuts,
        SUM(hitByPitch)            AS hitByPitch,
        SUM(singles)+SUM(doubles)+SUM(triples)+SUM(homeRuns) AS hits,
        SUM(homeRuns)              AS homeRuns,
        SUM(intentionalWalks)      AS intentionalWalks,
        SUM(lineOuts)              AS lineOuts,
        SUM(passedBalls)           AS passedBalls,
        SUM(popOuts)               AS popOuts,
        SUM(runsBattedIn)          AS runsBattedIn,
        SUM(sacBunts)              AS sacBunts,
        SUM(sacFlies)              AS sacFlies,
        SUM(singles)               AS singles,
        SUM(strikeOuts)            AS strikeOuts,
        SUM(triples)               AS triples,
        SUM(walks)                 AS walks,
        SUM(wildPitches)           AS wildPitches,
        SUM(balls)                 AS balls,
        SUM(ballsPitchOut)         AS ballsPitchOut,
        SUM(ballsInDirt)           AS ballsInDirt,
        SUM(intentBalls)           AS intentBalls,
        SUM(fouls)                 AS fouls,
        SUM(foulBunts)             AS foulBunts,
        SUM(foulTips)              AS foulTips,
        SUM(foulPitchOuts)         AS foulPitchOuts,
        SUM(hitIntoPlay)           AS hitIntoPlay,
        SUM(pitches)               AS pitches,
        SUM(pitchOuts)             AS pitchOuts,
        SUM(strikes)               AS strikes,
        SUM(strikesCalled)         AS strikesCalled,
        SUM(strikesPitchOuts)      AS strikesPitchOuts,
        SUM(missedBunts)           AS missedBunts,
        SUM(swingAndMissStrikes)   AS swingAndMissStrikes,
        SUM(swingsPitchOuts)       AS swingsPitchOuts,
        SUM(swings)                AS swings,
        SUM(swingsZeroAndZero)     AS swingsZeroAndZero,
        SUM(swingsZeroAndOne)      AS swingsZeroAndOne,
        SUM(swingsZeroAndTwo)      AS swingsZeroAndTwo,
        SUM(swingsOneAndZero)      AS swingsOneAndZero,
        SUM(swingsOneAndOne)       AS swingsOneAndOne,
        SUM(swingsOneAndTwo)       AS swingsOneAndTwo,
        SUM(swingsTwoAndZero)      AS swingsTwoAndZero,
        SUM(swingsTwoAndOne)       AS swingsTwoAndOne,
        SUM(swingsTwoAndTwo)       AS swingsTwoAndTwo,
        SUM(swingsThreeAndZero)    AS swingsThreeAndZero,
        SUM(swingsThreeAndOne)     AS swingsThreeAndOne,
        SUM(swingsThreeAndTwo)     AS swingsThreeAndTwo,
        SUM(flyBalls)              AS flyBalls,
        SUM(groundBalls)           AS groundBalls,
        SUM(lineDrives)            AS lineDrives,
        SUM(popUps)                AS popUps,
        SUM(groundBunts)           AS groundBunts,
        SUM(popupBunts)            AS popupBunts,
        SUM(lineDriveBunts)        AS lineDriveBunts,
        169487603      AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_VENUEID_TEAMID_TEAMTYPE'  AS groupingDescription
FROM data
GROUP BY majorLeagueId, seasonId, gameType2, venueId, teamId, teamType;


-- ── Grouping 219792182: MAJORLEAGUEID_SEASONID_GAMETYPE2_VENUEID_TEAMTYPE ──────────────────────────────────────────────
INSERT INTO agg_batting_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        venueId,
        officialId,
        opposingTeamId,
        atbats,
        balks,
        batterInterferences,
        bunts,
        catcherInterferences,
        doubles,
        fanInterferences,
        fieldErrors,
        fieldersChoice,
        flyouts,
        forceOuts,
        games,
        groundedIntoDoublePlays,
        groundedIntoTriplePlays,
        groundOuts,
        hitByPitch,
        hits,
        homeRuns,
        intentionalWalks,
        lineOuts,
        passedBalls,
        popOuts,
        runsBattedIn,
        sacBunts,
        sacFlies,
        singles,
        strikeOuts,
        triples,
        walks,
        wildPitches,
        balls,
        ballsPitchOut,
        ballsInDirt,
        intentBalls,
        fouls,
        foulBunts,
        foulTips,
        foulPitchOuts,
        hitIntoPlay,
        pitches,
        pitchOuts,
        strikes,
        strikesCalled,
        strikesPitchOuts,
        missedBunts,
        swingAndMissStrikes,
        swingsPitchOuts,
        swings,
        swingsZeroAndZero,
        swingsZeroAndOne,
        swingsZeroAndTwo,
        swingsOneAndZero,
        swingsOneAndOne,
        swingsOneAndTwo,
        swingsTwoAndZero,
        swingsTwoAndOne,
        swingsTwoAndTwo,
        swingsThreeAndZero,
        swingsThreeAndOne,
        swingsThreeAndTwo,
        flyBalls,
        groundBalls,
        lineDrives,
        popUps,
        groundBunts,
        popupBunts,
        lineDriveBunts,
        groupingId,
        groupingDescription
)
WITH bs AS (
    SELECT *, pitchingTeamId AS opposingTeamId
    FROM game_player_split_stats
),
g AS (
    SELECT majorLeagueId, seasonId, gamePk, gameType2, venueId, homeTeamId
    FROM games
    WHERE gameType2 IN ('PS', 'RS')
),
officials AS (
    SELECT gamePk, officialId
    FROM game_officials
    WHERE position = 'Home Plate'
),
data AS (
    SELECT
        g.majorLeagueId, g.seasonId, g.gamePk, g.gameType2, g.venueId,
        CASE WHEN g.homeTeamId = bs.battingTeamId THEN 'home' ELSE 'away' END AS teamType,
        bs.battingTeamId  AS teamId,
        bs.batterId       AS playerId,
        bs.opposingTeamId,
        o.officialId,
        batSide, pitchHand, menOnBase,
        (batterInterferences + bunts + doubles + fanInterferences + fieldErrors
         + fieldersChoice + flyouts + forceOuts + groundedIntoDoublePlays
         + triplePlays + groundOuts + homeRuns + lineOuts + popOuts
         + singles + strikeOuts + triples) AS atbats,
        balks, batterInterferences, bunts, catcherInterferences, doubles,
        fanInterferences, fieldErrors, fieldersChoice, flyouts, forceOuts,
        groundedIntoDoublePlays, groundOuts, hitByPitch, homeRuns,
        intentionalWalks, lineOuts, passedBalls, popOuts, runsBattedIn,
        sacBunts, sacFlies, singles, strikeOuts, triples, triplePlays,
        walks, wildPitches,
        balls, ballsPitchOut, ballsInDirt, intentBalls, fouls, foulBunts,
        foulTips, foulPitchOuts, hitIntoPlay, pitches, pitchOuts, strikes,
        strikesCalled, strikesPitchOuts, missedBunts, swingAndMissStrikes,
        swingsPitchOuts, swings,
        swingsZeroAndZero, swingsZeroAndOne, swingsZeroAndTwo,
        swingsOneAndZero,  swingsOneAndOne,  swingsOneAndTwo,
        swingsTwoAndZero,  swingsTwoAndOne,  swingsTwoAndTwo,
        swingsThreeAndZero,swingsThreeAndOne, swingsThreeAndTwo,
        flyBalls, groundBalls, lineDrives, popUps,
        groundBunts, popupBunts, lineDriveBunts
    FROM g
    INNER JOIN bs       ON g.gamePk = bs.gamePk
    LEFT  JOIN officials o ON g.gamePk = o.gamePk
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        NULL AS teamId,
        teamType,
        NULL AS playerId,
        venueId,
        NULL AS officialId,
        NULL AS opposingTeamId,
        SUM(atbats)                AS atbats,
        SUM(balks)                 AS balks,
        SUM(batterInterferences)   AS batterInterferences,
        SUM(bunts)                 AS bunts,
        SUM(catcherInterferences)  AS catcherInterferences,
        SUM(doubles)               AS doubles,
        SUM(fanInterferences)      AS fanInterferences,
        SUM(fieldErrors)           AS fieldErrors,
        SUM(fieldersChoice)        AS fieldersChoice,
        SUM(flyouts)               AS flyouts,
        SUM(forceOuts)             AS forceOuts,
        COUNT(DISTINCT gamePk)     AS games,
        SUM(groundedIntoDoublePlays) AS groundedIntoDoublePlays,
        SUM(triplePlays)           AS groundedIntoTriplePlays,
        SUM(groundOuts)            AS groundOuts,
        SUM(hitByPitch)            AS hitByPitch,
        SUM(singles)+SUM(doubles)+SUM(triples)+SUM(homeRuns) AS hits,
        SUM(homeRuns)              AS homeRuns,
        SUM(intentionalWalks)      AS intentionalWalks,
        SUM(lineOuts)              AS lineOuts,
        SUM(passedBalls)           AS passedBalls,
        SUM(popOuts)               AS popOuts,
        SUM(runsBattedIn)          AS runsBattedIn,
        SUM(sacBunts)              AS sacBunts,
        SUM(sacFlies)              AS sacFlies,
        SUM(singles)               AS singles,
        SUM(strikeOuts)            AS strikeOuts,
        SUM(triples)               AS triples,
        SUM(walks)                 AS walks,
        SUM(wildPitches)           AS wildPitches,
        SUM(balls)                 AS balls,
        SUM(ballsPitchOut)         AS ballsPitchOut,
        SUM(ballsInDirt)           AS ballsInDirt,
        SUM(intentBalls)           AS intentBalls,
        SUM(fouls)                 AS fouls,
        SUM(foulBunts)             AS foulBunts,
        SUM(foulTips)              AS foulTips,
        SUM(foulPitchOuts)         AS foulPitchOuts,
        SUM(hitIntoPlay)           AS hitIntoPlay,
        SUM(pitches)               AS pitches,
        SUM(pitchOuts)             AS pitchOuts,
        SUM(strikes)               AS strikes,
        SUM(strikesCalled)         AS strikesCalled,
        SUM(strikesPitchOuts)      AS strikesPitchOuts,
        SUM(missedBunts)           AS missedBunts,
        SUM(swingAndMissStrikes)   AS swingAndMissStrikes,
        SUM(swingsPitchOuts)       AS swingsPitchOuts,
        SUM(swings)                AS swings,
        SUM(swingsZeroAndZero)     AS swingsZeroAndZero,
        SUM(swingsZeroAndOne)      AS swingsZeroAndOne,
        SUM(swingsZeroAndTwo)      AS swingsZeroAndTwo,
        SUM(swingsOneAndZero)      AS swingsOneAndZero,
        SUM(swingsOneAndOne)       AS swingsOneAndOne,
        SUM(swingsOneAndTwo)       AS swingsOneAndTwo,
        SUM(swingsTwoAndZero)      AS swingsTwoAndZero,
        SUM(swingsTwoAndOne)       AS swingsTwoAndOne,
        SUM(swingsTwoAndTwo)       AS swingsTwoAndTwo,
        SUM(swingsThreeAndZero)    AS swingsThreeAndZero,
        SUM(swingsThreeAndOne)     AS swingsThreeAndOne,
        SUM(swingsThreeAndTwo)     AS swingsThreeAndTwo,
        SUM(flyBalls)              AS flyBalls,
        SUM(groundBalls)           AS groundBalls,
        SUM(lineDrives)            AS lineDrives,
        SUM(popUps)                AS popUps,
        SUM(groundBunts)           AS groundBunts,
        SUM(popupBunts)            AS popupBunts,
        SUM(lineDriveBunts)        AS lineDriveBunts,
        219792182      AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_VENUEID_TEAMTYPE'  AS groupingDescription
FROM data
GROUP BY majorLeagueId, seasonId, gameType2, venueId, teamType;


-- ── Grouping 2195260724: MAJORLEAGUEID_SEASONID_GAMETYPE2_OFFICIALID ──────────────────────────────────────────────
INSERT INTO agg_batting_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        venueId,
        officialId,
        opposingTeamId,
        atbats,
        balks,
        batterInterferences,
        bunts,
        catcherInterferences,
        doubles,
        fanInterferences,
        fieldErrors,
        fieldersChoice,
        flyouts,
        forceOuts,
        games,
        groundedIntoDoublePlays,
        groundedIntoTriplePlays,
        groundOuts,
        hitByPitch,
        hits,
        homeRuns,
        intentionalWalks,
        lineOuts,
        passedBalls,
        popOuts,
        runsBattedIn,
        sacBunts,
        sacFlies,
        singles,
        strikeOuts,
        triples,
        walks,
        wildPitches,
        balls,
        ballsPitchOut,
        ballsInDirt,
        intentBalls,
        fouls,
        foulBunts,
        foulTips,
        foulPitchOuts,
        hitIntoPlay,
        pitches,
        pitchOuts,
        strikes,
        strikesCalled,
        strikesPitchOuts,
        missedBunts,
        swingAndMissStrikes,
        swingsPitchOuts,
        swings,
        swingsZeroAndZero,
        swingsZeroAndOne,
        swingsZeroAndTwo,
        swingsOneAndZero,
        swingsOneAndOne,
        swingsOneAndTwo,
        swingsTwoAndZero,
        swingsTwoAndOne,
        swingsTwoAndTwo,
        swingsThreeAndZero,
        swingsThreeAndOne,
        swingsThreeAndTwo,
        flyBalls,
        groundBalls,
        lineDrives,
        popUps,
        groundBunts,
        popupBunts,
        lineDriveBunts,
        groupingId,
        groupingDescription
)
WITH bs AS (
    SELECT *, pitchingTeamId AS opposingTeamId
    FROM game_player_split_stats
),
g AS (
    SELECT majorLeagueId, seasonId, gamePk, gameType2, venueId, homeTeamId
    FROM games
    WHERE gameType2 IN ('PS', 'RS')
),
officials AS (
    SELECT gamePk, officialId
    FROM game_officials
    WHERE position = 'Home Plate'
),
data AS (
    SELECT
        g.majorLeagueId, g.seasonId, g.gamePk, g.gameType2, g.venueId,
        CASE WHEN g.homeTeamId = bs.battingTeamId THEN 'home' ELSE 'away' END AS teamType,
        bs.battingTeamId  AS teamId,
        bs.batterId       AS playerId,
        bs.opposingTeamId,
        o.officialId,
        batSide, pitchHand, menOnBase,
        (batterInterferences + bunts + doubles + fanInterferences + fieldErrors
         + fieldersChoice + flyouts + forceOuts + groundedIntoDoublePlays
         + triplePlays + groundOuts + homeRuns + lineOuts + popOuts
         + singles + strikeOuts + triples) AS atbats,
        balks, batterInterferences, bunts, catcherInterferences, doubles,
        fanInterferences, fieldErrors, fieldersChoice, flyouts, forceOuts,
        groundedIntoDoublePlays, groundOuts, hitByPitch, homeRuns,
        intentionalWalks, lineOuts, passedBalls, popOuts, runsBattedIn,
        sacBunts, sacFlies, singles, strikeOuts, triples, triplePlays,
        walks, wildPitches,
        balls, ballsPitchOut, ballsInDirt, intentBalls, fouls, foulBunts,
        foulTips, foulPitchOuts, hitIntoPlay, pitches, pitchOuts, strikes,
        strikesCalled, strikesPitchOuts, missedBunts, swingAndMissStrikes,
        swingsPitchOuts, swings,
        swingsZeroAndZero, swingsZeroAndOne, swingsZeroAndTwo,
        swingsOneAndZero,  swingsOneAndOne,  swingsOneAndTwo,
        swingsTwoAndZero,  swingsTwoAndOne,  swingsTwoAndTwo,
        swingsThreeAndZero,swingsThreeAndOne, swingsThreeAndTwo,
        flyBalls, groundBalls, lineDrives, popUps,
        groundBunts, popupBunts, lineDriveBunts
    FROM g
    INNER JOIN bs       ON g.gamePk = bs.gamePk
    LEFT  JOIN officials o ON g.gamePk = o.gamePk
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        NULL AS teamId,
        NULL AS teamType,
        NULL AS playerId,
        NULL AS venueId,
        officialId,
        NULL AS opposingTeamId,
        SUM(atbats)                AS atbats,
        SUM(balks)                 AS balks,
        SUM(batterInterferences)   AS batterInterferences,
        SUM(bunts)                 AS bunts,
        SUM(catcherInterferences)  AS catcherInterferences,
        SUM(doubles)               AS doubles,
        SUM(fanInterferences)      AS fanInterferences,
        SUM(fieldErrors)           AS fieldErrors,
        SUM(fieldersChoice)        AS fieldersChoice,
        SUM(flyouts)               AS flyouts,
        SUM(forceOuts)             AS forceOuts,
        COUNT(DISTINCT gamePk)     AS games,
        SUM(groundedIntoDoublePlays) AS groundedIntoDoublePlays,
        SUM(triplePlays)           AS groundedIntoTriplePlays,
        SUM(groundOuts)            AS groundOuts,
        SUM(hitByPitch)            AS hitByPitch,
        SUM(singles)+SUM(doubles)+SUM(triples)+SUM(homeRuns) AS hits,
        SUM(homeRuns)              AS homeRuns,
        SUM(intentionalWalks)      AS intentionalWalks,
        SUM(lineOuts)              AS lineOuts,
        SUM(passedBalls)           AS passedBalls,
        SUM(popOuts)               AS popOuts,
        SUM(runsBattedIn)          AS runsBattedIn,
        SUM(sacBunts)              AS sacBunts,
        SUM(sacFlies)              AS sacFlies,
        SUM(singles)               AS singles,
        SUM(strikeOuts)            AS strikeOuts,
        SUM(triples)               AS triples,
        SUM(walks)                 AS walks,
        SUM(wildPitches)           AS wildPitches,
        SUM(balls)                 AS balls,
        SUM(ballsPitchOut)         AS ballsPitchOut,
        SUM(ballsInDirt)           AS ballsInDirt,
        SUM(intentBalls)           AS intentBalls,
        SUM(fouls)                 AS fouls,
        SUM(foulBunts)             AS foulBunts,
        SUM(foulTips)              AS foulTips,
        SUM(foulPitchOuts)         AS foulPitchOuts,
        SUM(hitIntoPlay)           AS hitIntoPlay,
        SUM(pitches)               AS pitches,
        SUM(pitchOuts)             AS pitchOuts,
        SUM(strikes)               AS strikes,
        SUM(strikesCalled)         AS strikesCalled,
        SUM(strikesPitchOuts)      AS strikesPitchOuts,
        SUM(missedBunts)           AS missedBunts,
        SUM(swingAndMissStrikes)   AS swingAndMissStrikes,
        SUM(swingsPitchOuts)       AS swingsPitchOuts,
        SUM(swings)                AS swings,
        SUM(swingsZeroAndZero)     AS swingsZeroAndZero,
        SUM(swingsZeroAndOne)      AS swingsZeroAndOne,
        SUM(swingsZeroAndTwo)      AS swingsZeroAndTwo,
        SUM(swingsOneAndZero)      AS swingsOneAndZero,
        SUM(swingsOneAndOne)       AS swingsOneAndOne,
        SUM(swingsOneAndTwo)       AS swingsOneAndTwo,
        SUM(swingsTwoAndZero)      AS swingsTwoAndZero,
        SUM(swingsTwoAndOne)       AS swingsTwoAndOne,
        SUM(swingsTwoAndTwo)       AS swingsTwoAndTwo,
        SUM(swingsThreeAndZero)    AS swingsThreeAndZero,
        SUM(swingsThreeAndOne)     AS swingsThreeAndOne,
        SUM(swingsThreeAndTwo)     AS swingsThreeAndTwo,
        SUM(flyBalls)              AS flyBalls,
        SUM(groundBalls)           AS groundBalls,
        SUM(lineDrives)            AS lineDrives,
        SUM(popUps)                AS popUps,
        SUM(groundBunts)           AS groundBunts,
        SUM(popupBunts)            AS popupBunts,
        SUM(lineDriveBunts)        AS lineDriveBunts,
        2195260724      AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_OFFICIALID'  AS groupingDescription
FROM data
GROUP BY majorLeagueId, seasonId, gameType2, officialId;


-- ── Grouping 3551444302: MAJORLEAGUEID_SEASONID_GAMETYPE2_OPPOSINGTEAMID ──────────────────────────────────────────────
INSERT INTO agg_batting_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        playerId,
        venueId,
        officialId,
        opposingTeamId,
        atbats,
        balks,
        batterInterferences,
        bunts,
        catcherInterferences,
        doubles,
        fanInterferences,
        fieldErrors,
        fieldersChoice,
        flyouts,
        forceOuts,
        games,
        groundedIntoDoublePlays,
        groundedIntoTriplePlays,
        groundOuts,
        hitByPitch,
        hits,
        homeRuns,
        intentionalWalks,
        lineOuts,
        passedBalls,
        popOuts,
        runsBattedIn,
        sacBunts,
        sacFlies,
        singles,
        strikeOuts,
        triples,
        walks,
        wildPitches,
        balls,
        ballsPitchOut,
        ballsInDirt,
        intentBalls,
        fouls,
        foulBunts,
        foulTips,
        foulPitchOuts,
        hitIntoPlay,
        pitches,
        pitchOuts,
        strikes,
        strikesCalled,
        strikesPitchOuts,
        missedBunts,
        swingAndMissStrikes,
        swingsPitchOuts,
        swings,
        swingsZeroAndZero,
        swingsZeroAndOne,
        swingsZeroAndTwo,
        swingsOneAndZero,
        swingsOneAndOne,
        swingsOneAndTwo,
        swingsTwoAndZero,
        swingsTwoAndOne,
        swingsTwoAndTwo,
        swingsThreeAndZero,
        swingsThreeAndOne,
        swingsThreeAndTwo,
        flyBalls,
        groundBalls,
        lineDrives,
        popUps,
        groundBunts,
        popupBunts,
        lineDriveBunts,
        groupingId,
        groupingDescription
)
WITH bs AS (
    SELECT *, pitchingTeamId AS opposingTeamId
    FROM game_player_split_stats
),
g AS (
    SELECT majorLeagueId, seasonId, gamePk, gameType2, venueId, homeTeamId
    FROM games
    WHERE gameType2 IN ('PS', 'RS')
),
officials AS (
    SELECT gamePk, officialId
    FROM game_officials
    WHERE position = 'Home Plate'
),
data AS (
    SELECT
        g.majorLeagueId, g.seasonId, g.gamePk, g.gameType2, g.venueId,
        CASE WHEN g.homeTeamId = bs.battingTeamId THEN 'home' ELSE 'away' END AS teamType,
        bs.battingTeamId  AS teamId,
        bs.batterId       AS playerId,
        bs.opposingTeamId,
        o.officialId,
        batSide, pitchHand, menOnBase,
        (batterInterferences + bunts + doubles + fanInterferences + fieldErrors
         + fieldersChoice + flyouts + forceOuts + groundedIntoDoublePlays
         + triplePlays + groundOuts + homeRuns + lineOuts + popOuts
         + singles + strikeOuts + triples) AS atbats,
        balks, batterInterferences, bunts, catcherInterferences, doubles,
        fanInterferences, fieldErrors, fieldersChoice, flyouts, forceOuts,
        groundedIntoDoublePlays, groundOuts, hitByPitch, homeRuns,
        intentionalWalks, lineOuts, passedBalls, popOuts, runsBattedIn,
        sacBunts, sacFlies, singles, strikeOuts, triples, triplePlays,
        walks, wildPitches,
        balls, ballsPitchOut, ballsInDirt, intentBalls, fouls, foulBunts,
        foulTips, foulPitchOuts, hitIntoPlay, pitches, pitchOuts, strikes,
        strikesCalled, strikesPitchOuts, missedBunts, swingAndMissStrikes,
        swingsPitchOuts, swings,
        swingsZeroAndZero, swingsZeroAndOne, swingsZeroAndTwo,
        swingsOneAndZero,  swingsOneAndOne,  swingsOneAndTwo,
        swingsTwoAndZero,  swingsTwoAndOne,  swingsTwoAndTwo,
        swingsThreeAndZero,swingsThreeAndOne, swingsThreeAndTwo,
        flyBalls, groundBalls, lineDrives, popUps,
        groundBunts, popupBunts, lineDriveBunts
    FROM g
    INNER JOIN bs       ON g.gamePk = bs.gamePk
    LEFT  JOIN officials o ON g.gamePk = o.gamePk
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        NULL AS teamId,
        NULL AS teamType,
        NULL AS playerId,
        NULL AS venueId,
        NULL AS officialId,
        opposingTeamId,
        SUM(atbats)                AS atbats,
        SUM(balks)                 AS balks,
        SUM(batterInterferences)   AS batterInterferences,
        SUM(bunts)                 AS bunts,
        SUM(catcherInterferences)  AS catcherInterferences,
        SUM(doubles)               AS doubles,
        SUM(fanInterferences)      AS fanInterferences,
        SUM(fieldErrors)           AS fieldErrors,
        SUM(fieldersChoice)        AS fieldersChoice,
        SUM(flyouts)               AS flyouts,
        SUM(forceOuts)             AS forceOuts,
        COUNT(DISTINCT gamePk)     AS games,
        SUM(groundedIntoDoublePlays) AS groundedIntoDoublePlays,
        SUM(triplePlays)           AS groundedIntoTriplePlays,
        SUM(groundOuts)            AS groundOuts,
        SUM(hitByPitch)            AS hitByPitch,
        SUM(singles)+SUM(doubles)+SUM(triples)+SUM(homeRuns) AS hits,
        SUM(homeRuns)              AS homeRuns,
        SUM(intentionalWalks)      AS intentionalWalks,
        SUM(lineOuts)              AS lineOuts,
        SUM(passedBalls)           AS passedBalls,
        SUM(popOuts)               AS popOuts,
        SUM(runsBattedIn)          AS runsBattedIn,
        SUM(sacBunts)              AS sacBunts,
        SUM(sacFlies)              AS sacFlies,
        SUM(singles)               AS singles,
        SUM(strikeOuts)            AS strikeOuts,
        SUM(triples)               AS triples,
        SUM(walks)                 AS walks,
        SUM(wildPitches)           AS wildPitches,
        SUM(balls)                 AS balls,
        SUM(ballsPitchOut)         AS ballsPitchOut,
        SUM(ballsInDirt)           AS ballsInDirt,
        SUM(intentBalls)           AS intentBalls,
        SUM(fouls)                 AS fouls,
        SUM(foulBunts)             AS foulBunts,
        SUM(foulTips)              AS foulTips,
        SUM(foulPitchOuts)         AS foulPitchOuts,
        SUM(hitIntoPlay)           AS hitIntoPlay,
        SUM(pitches)               AS pitches,
        SUM(pitchOuts)             AS pitchOuts,
        SUM(strikes)               AS strikes,
        SUM(strikesCalled)         AS strikesCalled,
        SUM(strikesPitchOuts)      AS strikesPitchOuts,
        SUM(missedBunts)           AS missedBunts,
        SUM(swingAndMissStrikes)   AS swingAndMissStrikes,
        SUM(swingsPitchOuts)       AS swingsPitchOuts,
        SUM(swings)                AS swings,
        SUM(swingsZeroAndZero)     AS swingsZeroAndZero,
        SUM(swingsZeroAndOne)      AS swingsZeroAndOne,
        SUM(swingsZeroAndTwo)      AS swingsZeroAndTwo,
        SUM(swingsOneAndZero)      AS swingsOneAndZero,
        SUM(swingsOneAndOne)       AS swingsOneAndOne,
        SUM(swingsOneAndTwo)       AS swingsOneAndTwo,
        SUM(swingsTwoAndZero)      AS swingsTwoAndZero,
        SUM(swingsTwoAndOne)       AS swingsTwoAndOne,
        SUM(swingsTwoAndTwo)       AS swingsTwoAndTwo,
        SUM(swingsThreeAndZero)    AS swingsThreeAndZero,
        SUM(swingsThreeAndOne)     AS swingsThreeAndOne,
        SUM(swingsThreeAndTwo)     AS swingsThreeAndTwo,
        SUM(flyBalls)              AS flyBalls,
        SUM(groundBalls)           AS groundBalls,
        SUM(lineDrives)            AS lineDrives,
        SUM(popUps)                AS popUps,
        SUM(groundBunts)           AS groundBunts,
        SUM(popupBunts)            AS popupBunts,
        SUM(lineDriveBunts)        AS lineDriveBunts,
        3551444302      AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_OPPOSINGTEAMID'  AS groupingDescription
FROM data
GROUP BY majorLeagueId, seasonId, gameType2, opposingTeamId;


COMMIT;
