-- ============================================================
-- update_table_attributes — SQLite3 static equivalent
-- Generated by update_table_attributes_sqlite.py
--
-- Each UPDATE is wrapped in a SAVEPOINT so that statements
-- referencing columns that don't exist in a given table are
-- rolled back silently (equivalent to MySQL's CONTINUE HANDLER).
--
-- Run with:  sqlite3 your_base.db < update_table_attributes.sql
-- ============================================================

BEGIN;

-- ── agg_batting_stats ───────────────────────────────────────────

-- majorLeague
SAVEPOINT before_agg_batting_stats_majorLeague;
UPDATE agg_batting_stats
SET majorLeague = (
    SELECT majorLeague
    FROM games
    WHERE games.majorLeagueId = agg_batting_stats.majorLeagueId
    LIMIT 1
)
WHERE EXISTS (
    SELECT 1 FROM games WHERE games.majorLeagueId = agg_batting_stats.majorLeagueId
);
RELEASE SAVEPOINT before_agg_batting_stats_majorLeague;

-- playerName
SAVEPOINT before_agg_batting_stats_playerName;
UPDATE agg_batting_stats
SET playerName = (
    SELECT firstName || ' ' || lastName
    FROM players
    WHERE players.playerId = agg_batting_stats.playerId
    LIMIT 1
)
WHERE agg_batting_stats.playerId IS NOT NULL;
RELEASE SAVEPOINT before_agg_batting_stats_playerName;

-- teamName
SAVEPOINT before_agg_batting_stats_teamName;
UPDATE agg_batting_stats
SET teamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_batting_stats.majorLeagueId
      AND games.seasonId      = agg_batting_stats.seasonId
      AND games.homeTeamId    = agg_batting_stats.teamId
    LIMIT 1
)
WHERE agg_batting_stats.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_batting_stats_teamName;

-- venueName
SAVEPOINT before_agg_batting_stats_venueName;
UPDATE agg_batting_stats
SET venueName = (
    SELECT venueName
    FROM games
    WHERE games.venueId = agg_batting_stats.venueId
    LIMIT 1
)
WHERE agg_batting_stats.venueId IS NOT NULL;
RELEASE SAVEPOINT before_agg_batting_stats_venueName;

-- officialName
SAVEPOINT before_agg_batting_stats_officialName;
UPDATE agg_batting_stats
SET officialName = (
    SELECT firstName || ' ' || lastName
    FROM officials
    WHERE officials.officialId = agg_batting_stats.officialId
    LIMIT 1
)
WHERE agg_batting_stats.officialId IS NOT NULL;
RELEASE SAVEPOINT before_agg_batting_stats_officialName;

-- opposingTeamName
SAVEPOINT before_agg_batting_stats_opposingTeamName;
UPDATE agg_batting_stats
SET opposingTeamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_batting_stats.majorLeagueId
      AND games.seasonId      = agg_batting_stats.seasonId
      AND games.homeTeamId    = agg_batting_stats.teamId
    LIMIT 1
)
WHERE agg_batting_stats.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_batting_stats_opposingTeamName;

-- ── agg_pitching_split_stats ────────────────────────────────────

-- majorLeague
SAVEPOINT before_agg_pitching_split_stats_majorLeague;
UPDATE agg_pitching_split_stats
SET majorLeague = (
    SELECT majorLeague
    FROM games
    WHERE games.majorLeagueId = agg_pitching_split_stats.majorLeagueId
    LIMIT 1
)
WHERE EXISTS (
    SELECT 1 FROM games WHERE games.majorLeagueId = agg_pitching_split_stats.majorLeagueId
);
RELEASE SAVEPOINT before_agg_pitching_split_stats_majorLeague;

-- playerName
SAVEPOINT before_agg_pitching_split_stats_playerName;
UPDATE agg_pitching_split_stats
SET playerName = (
    SELECT firstName || ' ' || lastName
    FROM players
    WHERE players.playerId = agg_pitching_split_stats.playerId
    LIMIT 1
)
WHERE agg_pitching_split_stats.playerId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_split_stats_playerName;

-- teamName
SAVEPOINT before_agg_pitching_split_stats_teamName;
UPDATE agg_pitching_split_stats
SET teamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_pitching_split_stats.majorLeagueId
      AND games.seasonId      = agg_pitching_split_stats.seasonId
      AND games.homeTeamId    = agg_pitching_split_stats.teamId
    LIMIT 1
)
WHERE agg_pitching_split_stats.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_split_stats_teamName;

-- venueName
SAVEPOINT before_agg_pitching_split_stats_venueName;
UPDATE agg_pitching_split_stats
SET venueName = (
    SELECT venueName
    FROM games
    WHERE games.venueId = agg_pitching_split_stats.venueId
    LIMIT 1
)
WHERE agg_pitching_split_stats.venueId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_split_stats_venueName;

-- officialName
SAVEPOINT before_agg_pitching_split_stats_officialName;
UPDATE agg_pitching_split_stats
SET officialName = (
    SELECT firstName || ' ' || lastName
    FROM officials
    WHERE officials.officialId = agg_pitching_split_stats.officialId
    LIMIT 1
)
WHERE agg_pitching_split_stats.officialId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_split_stats_officialName;

-- opposingTeamName
SAVEPOINT before_agg_pitching_split_stats_opposingTeamName;
UPDATE agg_pitching_split_stats
SET opposingTeamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_pitching_split_stats.majorLeagueId
      AND games.seasonId      = agg_pitching_split_stats.seasonId
      AND games.homeTeamId    = agg_pitching_split_stats.teamId
    LIMIT 1
)
WHERE agg_pitching_split_stats.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_split_stats_opposingTeamName;

-- ── agg_pitching_stats ──────────────────────────────────────────

-- majorLeague
SAVEPOINT before_agg_pitching_stats_majorLeague;
UPDATE agg_pitching_stats
SET majorLeague = (
    SELECT majorLeague
    FROM games
    WHERE games.majorLeagueId = agg_pitching_stats.majorLeagueId
    LIMIT 1
)
WHERE EXISTS (
    SELECT 1 FROM games WHERE games.majorLeagueId = agg_pitching_stats.majorLeagueId
);
RELEASE SAVEPOINT before_agg_pitching_stats_majorLeague;

-- playerName
SAVEPOINT before_agg_pitching_stats_playerName;
UPDATE agg_pitching_stats
SET playerName = (
    SELECT firstName || ' ' || lastName
    FROM players
    WHERE players.playerId = agg_pitching_stats.playerId
    LIMIT 1
)
WHERE agg_pitching_stats.playerId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_stats_playerName;

-- teamName
SAVEPOINT before_agg_pitching_stats_teamName;
UPDATE agg_pitching_stats
SET teamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_pitching_stats.majorLeagueId
      AND games.seasonId      = agg_pitching_stats.seasonId
      AND games.homeTeamId    = agg_pitching_stats.teamId
    LIMIT 1
)
WHERE agg_pitching_stats.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_stats_teamName;

-- venueName
SAVEPOINT before_agg_pitching_stats_venueName;
UPDATE agg_pitching_stats
SET venueName = (
    SELECT venueName
    FROM games
    WHERE games.venueId = agg_pitching_stats.venueId
    LIMIT 1
)
WHERE agg_pitching_stats.venueId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_stats_venueName;

-- officialName
SAVEPOINT before_agg_pitching_stats_officialName;
UPDATE agg_pitching_stats
SET officialName = (
    SELECT firstName || ' ' || lastName
    FROM officials
    WHERE officials.officialId = agg_pitching_stats.officialId
    LIMIT 1
)
WHERE agg_pitching_stats.officialId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_stats_officialName;

-- opposingTeamName
SAVEPOINT before_agg_pitching_stats_opposingTeamName;
UPDATE agg_pitching_stats
SET opposingTeamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_pitching_stats.majorLeagueId
      AND games.seasonId      = agg_pitching_stats.seasonId
      AND games.homeTeamId    = agg_pitching_stats.teamId
    LIMIT 1
)
WHERE agg_pitching_stats.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_stats_opposingTeamName;

-- ── agg_pitching_balls_in_play_heatmaps ─────────────────────────

-- majorLeague
SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_majorLeague;
UPDATE agg_pitching_balls_in_play_heatmaps
SET majorLeague = (
    SELECT majorLeague
    FROM games
    WHERE games.majorLeagueId = agg_pitching_balls_in_play_heatmaps.majorLeagueId
    LIMIT 1
)
WHERE EXISTS (
    SELECT 1 FROM games WHERE games.majorLeagueId = agg_pitching_balls_in_play_heatmaps.majorLeagueId
);
RELEASE SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_majorLeague;

-- playerName
SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_playerName;
UPDATE agg_pitching_balls_in_play_heatmaps
SET playerName = (
    SELECT firstName || ' ' || lastName
    FROM players
    WHERE players.playerId = agg_pitching_balls_in_play_heatmaps.playerId
    LIMIT 1
)
WHERE agg_pitching_balls_in_play_heatmaps.playerId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_playerName;

-- teamName
SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_teamName;
UPDATE agg_pitching_balls_in_play_heatmaps
SET teamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_pitching_balls_in_play_heatmaps.majorLeagueId
      AND games.seasonId      = agg_pitching_balls_in_play_heatmaps.seasonId
      AND games.homeTeamId    = agg_pitching_balls_in_play_heatmaps.teamId
    LIMIT 1
)
WHERE agg_pitching_balls_in_play_heatmaps.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_teamName;

-- venueName
SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_venueName;
UPDATE agg_pitching_balls_in_play_heatmaps
SET venueName = (
    SELECT venueName
    FROM games
    WHERE games.venueId = agg_pitching_balls_in_play_heatmaps.venueId
    LIMIT 1
)
WHERE agg_pitching_balls_in_play_heatmaps.venueId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_venueName;

-- officialName
SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_officialName;
UPDATE agg_pitching_balls_in_play_heatmaps
SET officialName = (
    SELECT firstName || ' ' || lastName
    FROM officials
    WHERE officials.officialId = agg_pitching_balls_in_play_heatmaps.officialId
    LIMIT 1
)
WHERE agg_pitching_balls_in_play_heatmaps.officialId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_officialName;

-- opposingTeamName
SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_opposingTeamName;
UPDATE agg_pitching_balls_in_play_heatmaps
SET opposingTeamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_pitching_balls_in_play_heatmaps.majorLeagueId
      AND games.seasonId      = agg_pitching_balls_in_play_heatmaps.seasonId
      AND games.homeTeamId    = agg_pitching_balls_in_play_heatmaps.teamId
    LIMIT 1
)
WHERE agg_pitching_balls_in_play_heatmaps.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_pitching_balls_in_play_heatmaps_opposingTeamName;

-- ── agg_fielding_stats ──────────────────────────────────────────

-- majorLeague
SAVEPOINT before_agg_fielding_stats_majorLeague;
UPDATE agg_fielding_stats
SET majorLeague = (
    SELECT majorLeague
    FROM games
    WHERE games.majorLeagueId = agg_fielding_stats.majorLeagueId
    LIMIT 1
)
WHERE EXISTS (
    SELECT 1 FROM games WHERE games.majorLeagueId = agg_fielding_stats.majorLeagueId
);
RELEASE SAVEPOINT before_agg_fielding_stats_majorLeague;

-- playerName
SAVEPOINT before_agg_fielding_stats_playerName;
UPDATE agg_fielding_stats
SET playerName = (
    SELECT firstName || ' ' || lastName
    FROM players
    WHERE players.playerId = agg_fielding_stats.playerId
    LIMIT 1
)
WHERE agg_fielding_stats.playerId IS NOT NULL;
RELEASE SAVEPOINT before_agg_fielding_stats_playerName;

-- teamName
SAVEPOINT before_agg_fielding_stats_teamName;
UPDATE agg_fielding_stats
SET teamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_fielding_stats.majorLeagueId
      AND games.seasonId      = agg_fielding_stats.seasonId
      AND games.homeTeamId    = agg_fielding_stats.teamId
    LIMIT 1
)
WHERE agg_fielding_stats.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_fielding_stats_teamName;

-- venueName
SAVEPOINT before_agg_fielding_stats_venueName;
UPDATE agg_fielding_stats
SET venueName = (
    SELECT venueName
    FROM games
    WHERE games.venueId = agg_fielding_stats.venueId
    LIMIT 1
)
WHERE agg_fielding_stats.venueId IS NOT NULL;
RELEASE SAVEPOINT before_agg_fielding_stats_venueName;

-- officialName
SAVEPOINT before_agg_fielding_stats_officialName;
UPDATE agg_fielding_stats
SET officialName = (
    SELECT firstName || ' ' || lastName
    FROM officials
    WHERE officials.officialId = agg_fielding_stats.officialId
    LIMIT 1
)
WHERE agg_fielding_stats.officialId IS NOT NULL;
RELEASE SAVEPOINT before_agg_fielding_stats_officialName;

-- opposingTeamName
SAVEPOINT before_agg_fielding_stats_opposingTeamName;
UPDATE agg_fielding_stats
SET opposingTeamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_fielding_stats.majorLeagueId
      AND games.seasonId      = agg_fielding_stats.seasonId
      AND games.homeTeamId    = agg_fielding_stats.teamId
    LIMIT 1
)
WHERE agg_fielding_stats.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_fielding_stats_opposingTeamName;

-- ── pf_park_factors ─────────────────────────────────────────────

-- majorLeague
SAVEPOINT before_pf_park_factors_majorLeague;
UPDATE pf_park_factors
SET majorLeague = (
    SELECT majorLeague
    FROM games
    WHERE games.majorLeagueId = pf_park_factors.majorLeagueId
    LIMIT 1
)
WHERE EXISTS (
    SELECT 1 FROM games WHERE games.majorLeagueId = pf_park_factors.majorLeagueId
);
RELEASE SAVEPOINT before_pf_park_factors_majorLeague;

-- playerName
SAVEPOINT before_pf_park_factors_playerName;
UPDATE pf_park_factors
SET playerName = (
    SELECT firstName || ' ' || lastName
    FROM players
    WHERE players.playerId = pf_park_factors.playerId
    LIMIT 1
)
WHERE pf_park_factors.playerId IS NOT NULL;
RELEASE SAVEPOINT before_pf_park_factors_playerName;

-- teamName
SAVEPOINT before_pf_park_factors_teamName;
UPDATE pf_park_factors
SET teamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = pf_park_factors.majorLeagueId
      AND games.seasonId      = pf_park_factors.seasonId
      AND games.homeTeamId    = pf_park_factors.teamId
    LIMIT 1
)
WHERE pf_park_factors.teamId IS NOT NULL;
RELEASE SAVEPOINT before_pf_park_factors_teamName;

-- venueName
SAVEPOINT before_pf_park_factors_venueName;
UPDATE pf_park_factors
SET venueName = (
    SELECT venueName
    FROM games
    WHERE games.venueId = pf_park_factors.venueId
    LIMIT 1
)
WHERE pf_park_factors.venueId IS NOT NULL;
RELEASE SAVEPOINT before_pf_park_factors_venueName;

-- officialName
SAVEPOINT before_pf_park_factors_officialName;
UPDATE pf_park_factors
SET officialName = (
    SELECT firstName || ' ' || lastName
    FROM officials
    WHERE officials.officialId = pf_park_factors.officialId
    LIMIT 1
)
WHERE pf_park_factors.officialId IS NOT NULL;
RELEASE SAVEPOINT before_pf_park_factors_officialName;

-- opposingTeamName
SAVEPOINT before_pf_park_factors_opposingTeamName;
UPDATE pf_park_factors
SET opposingTeamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = pf_park_factors.majorLeagueId
      AND games.seasonId      = pf_park_factors.seasonId
      AND games.homeTeamId    = pf_park_factors.teamId
    LIMIT 1
)
WHERE pf_park_factors.teamId IS NOT NULL;
RELEASE SAVEPOINT before_pf_park_factors_opposingTeamName;

-- ── pf_heat_map_park_factors ────────────────────────────────────

-- majorLeague
SAVEPOINT before_pf_heat_map_park_factors_majorLeague;
UPDATE pf_heat_map_park_factors
SET majorLeague = (
    SELECT majorLeague
    FROM games
    WHERE games.majorLeagueId = pf_heat_map_park_factors.majorLeagueId
    LIMIT 1
)
WHERE EXISTS (
    SELECT 1 FROM games WHERE games.majorLeagueId = pf_heat_map_park_factors.majorLeagueId
);
RELEASE SAVEPOINT before_pf_heat_map_park_factors_majorLeague;

-- playerName
SAVEPOINT before_pf_heat_map_park_factors_playerName;
UPDATE pf_heat_map_park_factors
SET playerName = (
    SELECT firstName || ' ' || lastName
    FROM players
    WHERE players.playerId = pf_heat_map_park_factors.playerId
    LIMIT 1
)
WHERE pf_heat_map_park_factors.playerId IS NOT NULL;
RELEASE SAVEPOINT before_pf_heat_map_park_factors_playerName;

-- teamName
SAVEPOINT before_pf_heat_map_park_factors_teamName;
UPDATE pf_heat_map_park_factors
SET teamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = pf_heat_map_park_factors.majorLeagueId
      AND games.seasonId      = pf_heat_map_park_factors.seasonId
      AND games.homeTeamId    = pf_heat_map_park_factors.teamId
    LIMIT 1
)
WHERE pf_heat_map_park_factors.teamId IS NOT NULL;
RELEASE SAVEPOINT before_pf_heat_map_park_factors_teamName;

-- venueName
SAVEPOINT before_pf_heat_map_park_factors_venueName;
UPDATE pf_heat_map_park_factors
SET venueName = (
    SELECT venueName
    FROM games
    WHERE games.venueId = pf_heat_map_park_factors.venueId
    LIMIT 1
)
WHERE pf_heat_map_park_factors.venueId IS NOT NULL;
RELEASE SAVEPOINT before_pf_heat_map_park_factors_venueName;

-- officialName
SAVEPOINT before_pf_heat_map_park_factors_officialName;
UPDATE pf_heat_map_park_factors
SET officialName = (
    SELECT firstName || ' ' || lastName
    FROM officials
    WHERE officials.officialId = pf_heat_map_park_factors.officialId
    LIMIT 1
)
WHERE pf_heat_map_park_factors.officialId IS NOT NULL;
RELEASE SAVEPOINT before_pf_heat_map_park_factors_officialName;

-- opposingTeamName
SAVEPOINT before_pf_heat_map_park_factors_opposingTeamName;
UPDATE pf_heat_map_park_factors
SET opposingTeamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = pf_heat_map_park_factors.majorLeagueId
      AND games.seasonId      = pf_heat_map_park_factors.seasonId
      AND games.homeTeamId    = pf_heat_map_park_factors.teamId
    LIMIT 1
)
WHERE pf_heat_map_park_factors.teamId IS NOT NULL;
RELEASE SAVEPOINT before_pf_heat_map_park_factors_opposingTeamName;

-- ── agg_team_performance_stats ──────────────────────────────────

-- majorLeague
SAVEPOINT before_agg_team_performance_stats_majorLeague;
UPDATE agg_team_performance_stats
SET majorLeague = (
    SELECT majorLeague
    FROM games
    WHERE games.majorLeagueId = agg_team_performance_stats.majorLeagueId
    LIMIT 1
)
WHERE EXISTS (
    SELECT 1 FROM games WHERE games.majorLeagueId = agg_team_performance_stats.majorLeagueId
);
RELEASE SAVEPOINT before_agg_team_performance_stats_majorLeague;

-- playerName
SAVEPOINT before_agg_team_performance_stats_playerName;
UPDATE agg_team_performance_stats
SET playerName = (
    SELECT firstName || ' ' || lastName
    FROM players
    WHERE players.playerId = agg_team_performance_stats.playerId
    LIMIT 1
)
WHERE agg_team_performance_stats.playerId IS NOT NULL;
RELEASE SAVEPOINT before_agg_team_performance_stats_playerName;

-- teamName
SAVEPOINT before_agg_team_performance_stats_teamName;
UPDATE agg_team_performance_stats
SET teamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_team_performance_stats.majorLeagueId
      AND games.seasonId      = agg_team_performance_stats.seasonId
      AND games.homeTeamId    = agg_team_performance_stats.teamId
    LIMIT 1
)
WHERE agg_team_performance_stats.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_team_performance_stats_teamName;

-- venueName
SAVEPOINT before_agg_team_performance_stats_venueName;
UPDATE agg_team_performance_stats
SET venueName = (
    SELECT venueName
    FROM games
    WHERE games.venueId = agg_team_performance_stats.venueId
    LIMIT 1
)
WHERE agg_team_performance_stats.venueId IS NOT NULL;
RELEASE SAVEPOINT before_agg_team_performance_stats_venueName;

-- officialName
SAVEPOINT before_agg_team_performance_stats_officialName;
UPDATE agg_team_performance_stats
SET officialName = (
    SELECT firstName || ' ' || lastName
    FROM officials
    WHERE officials.officialId = agg_team_performance_stats.officialId
    LIMIT 1
)
WHERE agg_team_performance_stats.officialId IS NOT NULL;
RELEASE SAVEPOINT before_agg_team_performance_stats_officialName;

-- opposingTeamName
SAVEPOINT before_agg_team_performance_stats_opposingTeamName;
UPDATE agg_team_performance_stats
SET opposingTeamName = (
    SELECT homeTeamName
    FROM games
    WHERE games.majorLeagueId = agg_team_performance_stats.majorLeagueId
      AND games.seasonId      = agg_team_performance_stats.seasonId
      AND games.homeTeamId    = agg_team_performance_stats.teamId
    LIMIT 1
)
WHERE agg_team_performance_stats.teamId IS NOT NULL;
RELEASE SAVEPOINT before_agg_team_performance_stats_opposingTeamName;

COMMIT;
