USE baseball;

DROP TABLE stg_box_player_pitching;

CREATE TABLE IF NOT EXISTS stg_box_player_pitching (
  airOuts DOUBLE,
  atBats DOUBLE,
  balls DOUBLE,
  baseOnBalls DOUBLE,
  battersFaced DOUBLE,
  blownSaves DOUBLE,
  catchersInterference DOUBLE,
  caughtStealing DOUBLE,
  completeGames DOUBLE,
  doubles DOUBLE,
  earnedRuns DOUBLE,
  gamesFinished DOUBLE,
  gamesPitched DOUBLE,
  gamesPlayed DOUBLE,
  gamesStarted DOUBLE,
  groundOuts DOUBLE,
  hitBatsmen DOUBLE,
  hits DOUBLE,
  holds DOUBLE,
  homeRuns DOUBLE,
  inheritedRunners DOUBLE,
  inheritedRunnersScored DOUBLE,
  intentionalWalks DOUBLE,
  losses DOUBLE,
  numberOfPitches DOUBLE,
  outs DOUBLE,
  pickoffs DOUBLE,
  pitchesThrown DOUBLE,
  rbi DOUBLE,
  runs DOUBLE,
  sacBunts DOUBLE,
  sacFlies DOUBLE,
  saveOpportunities DOUBLE,
  saves DOUBLE,
  shutouts DOUBLE,
  stolenBases DOUBLE,
  strikeOuts DOUBLE,
  strikes DOUBLE,
  triples DOUBLE,
  wildPitches DOUBLE,
  wins DOUBLE,
  gamePk INTEGER,
  teamId INTEGER,
  teamType VARCHAR(20),
  playerId INTEGER
) ENGINE = INNODB;
