source ./tablas/runners.sql
source ./tablas/game_officials.sql
source ./tablas/officials.sql
source ./tablas/game_player_split_stats.sql
source ./tablas/game_battery_fielding_stats.sql
source ./tablas/atbats.sql
source ./tablas/pitches.sql
source ./tablas/game_player_pitching_stats.sql
source ./tablas/fielding_credits.sql
source ./tablas/pickoffs.sql
source ./tablas/game_player_fielding_outs.sql
source ./tablas/transactions.sql
source ./tablas/game_player_fielding_stats.sql
source ./tablas/actions.sql
source ./tablas/game_player_batting_stats.sql
source ./tablas/game_player_balls_in_play_heatmaps.sql
source ./tablas/games.sql
source ./tablas/players.sql
source ./tablas/game_batting_orders.sql
source ./tablas/defensive_substitutions.sql
source ./tablas/game_player_positions.sql
source ./tablas/major_leagues.sql
source ./procedimientos/runners.sql
source ./procedimientos/game_officials.sql
source ./procedimientos/officials.sql
source ./procedimientos/game_player_split_stats.sql
source ./procedimientos/game_battery_fielding_stats.sql
source ./procedimientos/atbats.sql
source ./procedimientos/pitches.sql
source ./procedimientos/game_player_pitching_stats.sql
source ./procedimientos/fielding_credits.sql
source ./procedimientos/pickoffs.sql
source ./procedimientos/game_player_fielding_outs.sql
source ./procedimientos/transactions.sql
source ./procedimientos/game_player_fielding_stats.sql
source ./procedimientos/actions.sql
source ./procedimientos/game_player_batting_stats.sql
source ./procedimientos/game_player_balls_in_play_heatmaps.sql
source ./procedimientos/games.sql
source ./procedimientos/players.sql
source ./procedimientos/game_batting_orders.sql
source ./procedimientos/defensive_substitutions.sql
source ./procedimientos/game_player_positions.sql
source ./procedimientos/major_leagues.sql