/*
Generated from export_all_tables.py.
Run from shell: sqlite3 sqlite3_index_creation.sql
*/

.open baseball.db

CREATE INDEX groupingDescription_agg_team_performance_stats ON agg_team_performance_stats(groupingDescription);
CREATE INDEX groupingId_agg_team_performance_stats ON agg_team_performance_stats(groupingId);
CREATE INDEX majorLeagueId_agg_team_performance_stats ON agg_team_performance_stats(majorLeagueId);
CREATE INDEX seasonId_agg_team_performance_stats ON agg_team_performance_stats(seasonId);
CREATE INDEX teamId_agg_team_performance_stats ON agg_team_performance_stats(teamId);
CREATE INDEX venueId_agg_team_performance_stats ON agg_team_performance_stats(venueId);
CREATE INDEX gamePk_atBatIndex_atbats ON atbats(gamePk,atBatIndex);
CREATE INDEX gamePk_substitutionAtBatIndex_substitutionPlayIndex_defensive_substitutions ON defensive_substitutions(gamePk,substitutionAtBatIndex,substitutionPlayIndex);
CREATE INDEX gamePk_atBatIndex_playIndex_defensive_substitutions ON defensive_substitutions(gamePk,atBatIndex,playIndex);
CREATE INDEX gamePk_atBatIndex_fielding_credits ON fielding_credits(gamePk,atBatIndex);
CREATE INDEX gamePk_game_battery_fielding_stats ON game_battery_fielding_stats(gamePk);
CREATE INDEX gamePk_teamId_playerId_game_batting_orders ON game_batting_orders(gamePk,teamId,playerId);
CREATE INDEX gamePk_game_officials ON game_officials(gamePk);
CREATE INDEX gamePk_atBatIndex_game_player_balls_in_play_heatmaps ON game_player_balls_in_play_heatmaps(gamePk,atBatIndex);
CREATE INDEX gamePk_teamId_playerId_game_player_batting_stats ON game_player_batting_stats(gamePk,teamId,playerId);
CREATE INDEX gamePk_playerId_positionAbbrev_game_player_fielding_outs ON game_player_fielding_outs(gamePk,playerId,positionAbbrev);
CREATE INDEX gamePk_teamId_playerId_game_player_fielding_stats ON game_player_fielding_stats(gamePk,teamId,playerId);
CREATE INDEX gamePk_teamId_playerId_game_player_pitching_stats ON game_player_pitching_stats(gamePk,teamId,playerId);
CREATE INDEX gamePk_teamId_playerId_game_player_positions ON game_player_positions(gamePk,teamId,playerId);
CREATE INDEX gamePk_atBatIndex_game_player_split_stats ON game_player_split_stats(gamePk,atBatIndex);
CREATE INDEX majorLeagueId_major_leagues ON major_leagues(majorLeagueId);
CREATE INDEX officialId_officials ON officials(officialId);
CREATE INDEX groupingDescription_pf_heat_map_park_factors ON pf_heat_map_park_factors(groupingDescription);
CREATE INDEX groupingId_pf_heat_map_park_factors ON pf_heat_map_park_factors(groupingId);
CREATE INDEX majorLeagueId_pf_heat_map_park_factors ON pf_heat_map_park_factors(majorLeagueId);
CREATE INDEX seasonId_pf_heat_map_park_factors ON pf_heat_map_park_factors(seasonId);
CREATE INDEX venueId_pf_heat_map_park_factors ON pf_heat_map_park_factors(venueId);
CREATE INDEX groupingDescription_pf_park_factors ON pf_park_factors(groupingDescription);
CREATE INDEX groupingId_pf_park_factors ON pf_park_factors(groupingId);
CREATE INDEX majorLeagueId_pf_park_factors ON pf_park_factors(majorLeagueId);
CREATE INDEX seasonId_pf_park_factors ON pf_park_factors(seasonId);
CREATE INDEX venueId_pf_park_factors ON pf_park_factors(venueId);
CREATE INDEX gamePk_atBatIndex_pickoffs ON pickoffs(gamePk,atBatIndex);
CREATE INDEX gamePk_atBatIndex_pitches ON pitches(gamePk,atBatIndex);
CREATE INDEX playerId_players ON players(playerId);
CREATE INDEX groupingId_rem_event_run_value ON rem_event_run_value(groupingId);
CREATE INDEX majorLeagueId_rem_event_run_value ON rem_event_run_value(majorLeagueId);
CREATE INDEX venueId_rem_event_run_value ON rem_event_run_value(venueId);
CREATE INDEX gamePk_atBatIndex_playIndex_rem_play_by_play ON rem_play_by_play(gamePk,atBatIndex,playIndex);
CREATE INDEX groupingId_rem_run_expectancy_matrix ON rem_run_expectancy_matrix(groupingId);
CREATE INDEX majorLeagueId_rem_run_expectancy_matrix ON rem_run_expectancy_matrix(majorLeagueId);
CREATE INDEX seasonId_rem_run_expectancy_matrix ON rem_run_expectancy_matrix(seasonId);
CREATE INDEX venueId_rem_run_expectancy_matrix ON rem_run_expectancy_matrix(venueId);
CREATE INDEX gamePk_atBatIndex_runners ON runners(gamePk,atBatIndex);
CREATE INDEX majorLeagueId_seasonId_teamId_teams ON teams(majorLeagueId,seasonId,teamId);
CREATE INDEX groupingId_we_win_expectancy ON we_win_expectancy(groupingId);
CREATE INDEX majorLeagueId_we_win_expectancy ON we_win_expectancy(majorLeagueId);
CREATE INDEX seasonId_we_win_expectancy ON we_win_expectancy(seasonId);
CREATE INDEX groupingId_we_win_probability_added ON we_win_probability_added(groupingId);
CREATE INDEX majorLeagueId_we_win_probability_added ON we_win_probability_added(majorLeagueId);
CREATE INDEX playerId_we_win_probability_added ON we_win_probability_added(playerId);
CREATE INDEX teamId_we_win_probability_added ON we_win_probability_added(teamId);