-- ============================================================
-- agg_team_performance_stats cube — SQLite3 static equivalent
-- Generated by agg_team_performance_stats_sqlite.py
-- Run with:  sqlite3 your_base.db < agg_team_performance_stats.sql
-- ============================================================

BEGIN;

-- ── Grouping 3215925615: MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID ──────────────────────────────────────────────
INSERT INTO agg_team_performance_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        venueId,
        aggregationType,
        runs,
        runsAllowed,
        wins,
        losses,
        attendance,
        groupingId,
        groupingDescription
)
WITH g AS (
    SELECT
        majorLeagueId, seasonId, gameDate, gameType2,
        'home'      AS teamType,
        venueId,
        homeTeamId  AS teamId,
        homeScore   AS runs,
        awayScore   AS runsAllowed,
        CASE WHEN homeIsWinner = 1 THEN 1 ELSE 0 END AS wins,
        CASE WHEN awayIsWinner = 1 THEN 1 ELSE 0 END AS losses,
        attendance
    FROM games

    UNION ALL

    SELECT
        majorLeagueId, seasonId, gameDate, gameType2,
        'away'      AS teamType,
        venueId,
        awayTeamId  AS teamId,
        awayScore   AS runs,
        homeScore   AS runsAllowed,
        CASE WHEN awayIsWinner = 1 THEN 1 ELSE 0 END AS wins,
        CASE WHEN homeIsWinner = 1 THEN 1 ELSE 0 END AS losses,
        attendance
    FROM games
),
d AS (
    SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        NULL AS teamType,
        NULL AS venueId,
        SUM(runs)        AS runs,
        SUM(runsAllowed) AS runsAllowed,
        SUM(wins)        AS wins,
        SUM(losses)      AS losses,
        SUM(attendance)  AS attendance
    FROM g
    WHERE gameType2 IN ('RS', 'PS')
    GROUP BY majorLeagueId, seasonId, gameType2, teamId
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        NULL AS teamType,
        NULL AS venueId,
        SUM(runs) AS runs,
        SUM(runsAllowed) AS runsAllowed,
        SUM(wins) AS wins,
        SUM(losses) AS losses,
        SUM(attendance) AS attendance,
        'AGGREGATED' AS aggregationType,
        3215925615        AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID'    AS groupingDescription
FROM d
GROUP BY majorLeagueId, seasonId, gameType2, teamId;


-- ── Grouping 1730332978: MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID_TEAMTYPE ──────────────────────────────────────────────
INSERT INTO agg_team_performance_stats (
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        venueId,
        aggregationType,
        runs,
        runsAllowed,
        wins,
        losses,
        attendance,
        groupingId,
        groupingDescription
)
WITH g AS (
    SELECT
        majorLeagueId, seasonId, gameDate, gameType2,
        'home'      AS teamType,
        venueId,
        homeTeamId  AS teamId,
        homeScore   AS runs,
        awayScore   AS runsAllowed,
        CASE WHEN homeIsWinner = 1 THEN 1 ELSE 0 END AS wins,
        CASE WHEN awayIsWinner = 1 THEN 1 ELSE 0 END AS losses,
        attendance
    FROM games

    UNION ALL

    SELECT
        majorLeagueId, seasonId, gameDate, gameType2,
        'away'      AS teamType,
        venueId,
        awayTeamId  AS teamId,
        awayScore   AS runs,
        homeScore   AS runsAllowed,
        CASE WHEN awayIsWinner = 1 THEN 1 ELSE 0 END AS wins,
        CASE WHEN homeIsWinner = 1 THEN 1 ELSE 0 END AS losses,
        attendance
    FROM games
),
d AS (
    SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        NULL AS venueId,
        SUM(runs)        AS runs,
        SUM(runsAllowed) AS runsAllowed,
        SUM(wins)        AS wins,
        SUM(losses)      AS losses,
        SUM(attendance)  AS attendance
    FROM g
    WHERE gameType2 IN ('RS', 'PS')
    GROUP BY majorLeagueId, seasonId, gameType2, teamId, teamType
)
SELECT
        majorLeagueId,
        seasonId,
        gameType2,
        teamId,
        teamType,
        NULL AS venueId,
        SUM(runs) AS runs,
        SUM(runsAllowed) AS runsAllowed,
        SUM(wins) AS wins,
        SUM(losses) AS losses,
        SUM(attendance) AS attendance,
        'AGGREGATED' AS aggregationType,
        1730332978        AS groupingId,
        'MAJORLEAGUEID_SEASONID_GAMETYPE2_TEAMID_TEAMTYPE'    AS groupingDescription
FROM d
GROUP BY majorLeagueId, seasonId, gameType2, teamId, teamType;


COMMIT;
