# Dictionary mapping each position abbreviation to details about the position

position_typ_map = {
    "P": {
        "code": "1",
        "displayName": "Pitcher",
        "fielder": False,
        "formalName": "Pitcher",
        "fullName": "Pitcher",
        "gamePosition": True,
        "outfield": False,
        "pitcher": True,
        "shortName": "Pitcher",
        "type": "Pitcher"
    },
    "C": {
        "code": "2",
        "displayName": "Catcher",
        "fielder": True,
        "formalName": "Catcher",
        "fullName": "Catcher",
        "gamePosition": True,
        "outfield": False,
        "pitcher": False,
        "shortName": "Catcher",
        "type": "Catcher"
    },
    "1B": {
        "code": "3",
        "displayName": "First Base",
        "fielder": True,
        "formalName": "First Baseman",
        "fullName": "First Base",
        "gamePosition": True,
        "outfield": False,
        "pitcher": False,
        "shortName": "1st Base",
        "type": "Infielder"
    },
    "2B": {
        "code": "4",
        "displayName": "Second Base",
        "fielder": True,
        "formalName": "Second Baseman",
        "fullName": "Second Base",
        "gamePosition": True,
        "outfield": False,
        "pitcher": False,
        "shortName": "2nd Base",
        "type": "Infielder"
    },
    "3B": {
        "code": "5",
        "displayName": "Third Base",
        "fielder": True,
        "formalName": "Third Baseman",
        "fullName": "Third Base",
        "gamePosition": True,
        "outfield": False,
        "pitcher": False,
        "shortName": "3rd Base",
        "type": "Infielder"
    },
    "SS": {
        "code": "6",
        "displayName": "Shortstop",
        "fielder": True,
        "formalName": "Shortstop",
        "fullName": "Shortstop",
        "gamePosition": True,
        "outfield": False,
        "pitcher": False,
        "shortName": "Shortstop",
        "type": "Infielder"
    },
    "LF": {
        "code": "7",
        "displayName": "Outfielder",
        "fielder": True,
        "formalName": "Left Fielder",
        "fullName": "Outfielder",
        "gamePosition": True,
        "outfield": True,
        "pitcher": False,
        "shortName": "Left Field",
        "type": "Outfielder"
    },
    "CF": {
        "code": "8",
        "displayName": "Outfielder",
        "fielder": True,
        "formalName": "Center Fielder",
        "fullName": "Outfielder",
        "gamePosition": True,
        "outfield": True,
        "pitcher": False,
        "shortName": "Center Field",
        "type": "Outfielder"
    },
    "RF": {
        "code": "9",
        "displayName": "Outfielder",
        "fielder": True,
        "formalName": "Right Fielder",
        "fullName": "Outfielder",
        "gamePosition": True,
        "outfield": True,
        "pitcher": False,
        "shortName": "Right Field",
        "type": "Outfielder"
    },
    "DH": {
        "code": "10",
        "displayName": "Designated Hitter",
        "fielder": False,
        "formalName": "Designated Hitter",
        "fullName": "Designated Hitter",
        "gamePosition": True,
        "outfield": False,
        "pitcher": False,
        "shortName": "Designated Hitter",
        "type": "Hitter"
    },
    "PH": {
        "code": "11",
        "displayName": "Pinch Hitter",
        "fielder": False,
        "formalName": "Pinch Hitter",
        "fullName": "Pinch Hitter",
        "gamePosition": True,
        "outfield": False,
        "pitcher": False,
        "shortName": "Pinch Hitter",
        "type": "Hitter"
    },
    "PR": {
        "code": "12",
        "displayName": "Pinch Runner",
        "fielder": False,
        "formalName": "Pinch Runner",
        "fullName": "Pinch Runner",
        "gamePosition": True,
        "outfield": False,
        "pitcher": False,
        "shortName": "Pinch Runner",
        "type": "Runner"
    },
    "EH": {
        "code": "13",
        "displayName": "Extra Hitter",
        "fielder": False,
        "formalName": "Extra Hitter",
        "fullName": "Extra Hitter",
        "gamePosition": True,
        "outfield": False,
        "pitcher": False,
        "shortName": "Extra Hitter",
        "type": "Hitter"
    },
    "BR": {
        "code": "BR",
        "displayName": "Base Runner",
        "fielder": False,
        "formalName": "Base Runner",
        "fullName": "Base Runner",
        "gamePosition": False,
        "outfield": False,
        "pitcher": False,
        "shortName": "Base Runner",
        "type": "Runner"
    },
    "OF": {
        "code": "O",
        "displayName": "Outfield",
        "fielder": True,
        "formalName": "Outfield",
        "fullName": "Outfield",
        "gamePosition": False,
        "outfield": True,
        "pitcher": False,
        "shortName": "Outfield",
        "type": "Outfielder"
    },
    "IF": {
        "code": "I",
        "displayName": "Infield",
        "fielder": True,
        "formalName": "Infield",
        "fullName": "Infield",
        "gamePosition": False,
        "outfield": False,
        "pitcher": False,
        "shortName": "Infield",
        "type": "Infielder"
    },
    "SP": {
        "code": "S",
        "displayName": "Starting Pitcher",
        "fielder": False,
        "formalName": "Starting Pitcher",
        "fullName": "Starting Pitcher",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Starting Pitcher",
        "type": "Pitcher"
    },
    "RP": {
        "code": "E",
        "displayName": "Relief Pitcher",
        "fielder": False,
        "formalName": "Relief Pitcher",
        "fullName": "Relief Pitcher",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Relief Pitcher",
        "type": "Pitcher"
    },
    "CP": {
        "code": "C",
        "displayName": "Closer",
        "fielder": False,
        "formalName": "Closer",
        "fullName": "Closer",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Closer",
        "type": "Pitcher"
    },
    "UT": {
        "code": "U",
        "displayName": "Utility",
        "fielder": True,
        "formalName": "Utility",
        "fullName": "Utility",
        "gamePosition": False,
        "outfield": False,
        "pitcher": False,
        "shortName": "Utility",
        "type": "Infielder"
    },
    "UI": {
        "code": "V",
        "displayName": "Utility Infielder",
        "fielder": True,
        "formalName": "Utility Infielder",
        "fullName": "Utility Infielder",
        "gamePosition": False,
        "outfield": False,
        "pitcher": False,
        "shortName": "Utility Infielder",
        "type": "Infielder"
    },
    "UO": {
        "code": "W",
        "displayName": "Utility Outfielder",
        "fielder": True,
        "formalName": "Utility Outfielder",
        "fullName": "Utility Outfielder",
        "gamePosition": False,
        "outfield": True,
        "pitcher": False,
        "shortName": "Utility Outfielder",
        "type": "Outfielder"
    },
    "RHP": {
        "code": "K",
        "displayName": "Right-Handed Pitcher",
        "fielder": False,
        "formalName": "Right-Handed Pitcher",
        "fullName": "Right-Handed Pitcher",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Right-Handed Pitcher",
        "type": "Pitcher"
    },
    "LHP": {
        "code": "L",
        "displayName": "Left-Handed Pitcher",
        "fielder": False,
        "formalName": "Left-Handed Pitcher",
        "fullName": "Left-Handed Pitcher",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Left-Handed Pitcher",
        "type": "Pitcher"
    },
    "RHS": {
        "code": "M",
        "displayName": "Right-Handed Starter",
        "fielder": False,
        "formalName": "Right-Handed Starter",
        "fullName": "Right-Handed Starter",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Right-Handed Starter",
        "type": "Pitcher"
    },
    "LHS": {
        "code": "N",
        "displayName": "Left-Handed Starter",
        "fielder": False,
        "formalName": "Left-Handed Starter",
        "fullName": "Left-Handed Starter",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Left-Handed Starter",
        "type": "Pitcher"
    },
    "LHR": {
        "code": "G",
        "displayName": "Left-Handed Reliever",
        "fielder": False,
        "formalName": "Left-Handed Reliever",
        "fullName": "Left-Handed Reliever",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Left-Handed Reliever",
        "type": "Pitcher"
    },
    "RHR": {
        "code": "F",
        "displayName": "Right-Handed Reliever",
        "fielder": False,
        "formalName": "Right-Handed Reliever",
        "fullName": "Right-Handed Reliever",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Right-Handed Reliever",
        "type": "Pitcher"
    },
    "P-IF": {
        "code": "A",
        "displayName": "Pitcher - Infielder",
        "fielder": True,
        "formalName": "Pitcher - Infielder",
        "fullName": "Pitcher - Infielder",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Pitcher - Infielder",
        "type": "Two-Way Player"
    },
    "P-OF": {
        "code": "J",
        "displayName": "Pitcher - Outfielder",
        "fielder": True,
        "formalName": "Pitcher - Outfielder",
        "fullName": "Pitcher - Outfielder",
        "gamePosition": False,
        "outfield": True,
        "pitcher": True,
        "shortName": "Pitcher - Outfielder",
        "type": "Two-Way Player"
    },
    "P-UT": {
        "code": "Z",
        "displayName": "Pitcher - Utility",
        "fielder": True,
        "formalName": "Pitcher - Utility",
        "fullName": "Pitcher - Utility",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Pitcher - Utility",
        "type": "Two-Way Player"
    },
    "TWP": {
        "code": "Y",
        "displayName": "Two-Way Player",
        "fielder": False,
        "formalName": "Two-Way Player",
        "fullName": "Two-Way Player",
        "gamePosition": False,
        "outfield": False,
        "pitcher": True,
        "shortName": "Two-Way Player",
        "type": "Two-Way Player"
    },
    "B": {
        "code": "10",
        "displayName": "Batter",
        "fielder": False,
        "formalName": "Batter",
        "fullName": "Batter",
        "gamePosition": False,
        "outfield": False,
        "pitcher": False,
        "shortName": "Batter",
        "type": "Batter"
    },
    "X": {
        "code": "X",
        "displayName": "Unknown",
        "fielder": False,
        "formalName": "Unknown",
        "fullName": "Unknown",
        "gamePosition": False,
        "outfield": False,
        "pitcher": False,
        "shortName": "Unknown",
        "type": "Unknown"
    },
    "R1": {
        "code": "R1",
        "displayName": "Runner on First",
        "fielder": False,
        "formalName": "Runner on First",
        "fullName": "Runner on First",
        "gamePosition": False,
        "outfield": False,
        "pitcher": False,
        "shortName": "Runner on First",
        "type": "Runner"
    },
    "R2": {
        "code": "R2",
        "displayName": "Runner on Second",
        "fielder": False,
        "formalName": "Runner on Second",
        "fullName": "Runner on Second",
        "gamePosition": False,
        "outfield": False,
        "pitcher": False,
        "shortName": "Runner on Second",
        "type": "Runner"
    },
    "R3": {
        "code": "R3",
        "displayName": "Runner on Third",
        "fielder": False,
        "formalName": "Runner on Third",
        "fullName": "Runner on Third",
        "gamePosition": False,
        "outfield": False,
        "pitcher": False,
        "shortName": "Runner on Third",
        "type": "Runner"
    }
}