DROP TABLE IF EXISTS agg_batting_stats; 

CREATE TABLE agg_batting_stats (
groupingId INTEGER,
groupingDescription TEXT,
aggregationType TEXT,
majorLeagueId INTEGER,
seasonId REAL,
gameDate TEXT,
gameType2 TEXT,
teamType TEXT,
venueId REAL,
teamId REAL,
opposingTeamId REAL,
officialId REAL,
playerId REAL,
batSide TEXT,
pitchHand TEXT,
menOnBase TEXT,
games INTEGER,
atBats INTEGER,
balks INTEGER,
batterInterferences INTEGER,
bunts INTEGER,
catcherInterferences INTEGER,
caughtStealing REAL,
doubles INTEGER,
fanInterferences INTEGER,
fieldErrors INTEGER,
fieldersChoice INTEGER,
forceOuts INTEGER,
flyOuts INTEGER,
groundedIntoDoublePlays INTEGER,
groundedIntoTriplePlays INTEGER,
groundOuts INTEGER,
hitByPitch INTEGER,
hits INTEGER,
homeRuns INTEGER,
intentionalWalks INTEGER,
leftOnBase REAL,
lineOuts INTEGER,
passedBalls INTEGER,
pickoffs REAL,
plateAppearances REAL,
popOuts INTEGER,
runsBattedIn REAL,
runs REAL,
sacBunts INTEGER,
sacFlies INTEGER,
singles INTEGER,
stolenBases REAL,
stolenBaseAttempts REAL,
strikeOuts INTEGER,
totalBases REAL,
triples INTEGER,
unintentionalWalks REAL,
w
);

