DROP TABLE IF EXISTS games; 

CREATE TABLE games (
gamePk INTEGER,
gameType TEXT,
gameType2 TEXT,
seasonId REAL,
gameDate TEXT,
isTie REAL,
gameNumber INTEGER,
majorLeague TEXT,
majorLeagueId INTEGER,
doubleHeader TEXT,
dayNight TEXT,
scheduledInnings INTEGER,
gamesInSeries REAL,
seriesDescription TEXT,
ifNecessaryDescription TEXT,
gameId TEXT,
abstractGameState TEXT,
codedGameState TEXT,
detailedState TEXT,
awayWins INTEGER,
awayLosses INTEGER,
awayPct REAL,
awayScore INTEGER,
awayTeamId INTEGER,
awayIsWinner REAL,
homeWins INTEGER,
homeLosses INTEGER,
homePct REAL,
homeScore INTEGER,
homeTeamId INTEGER,
homeIsWinner REAL,
venueId INTEGER,
homeTeamName TEXT,
awayTeamName TEXT,
venueName TEXT,
weather TEXT,
wind TEXT,
attendance REAL
);

CREATE INDEX gamePk_games ON games(gamePk);