DROP TABLE IF EXISTS pitches; 

CREATE TABLE pitches (
gamePk INTEGER,
atBatIndex INTEGER,
playIndex INTEGER,
inning INTEGER,
halfInning TEXT,
battingTeamId INTEGER,
pitchingTeamId INTEGER,
batterId INTEGER,
pitcherId INTEGER,
pitchNumber INTEGER,
startBalls INTEGER,
startStrikes INTEGER,
endBalls INTEGER,
endStrikes INTEGER,
callCode TEXT,
callDescription TEXT,
callDescription2 TEXT,
code TEXT,
isInPlay INTEGER,
isStrike INTEGER,
isBall INTEGER,
typeCode TEXT,
typeDescription TEXT,
hasReview INTEGER,
runnerGoing INTEGER,
strikeZoneTop REAL,
strikeZoneBottom REAL,
x REAL,
y REAL,
x0 REAL,
y0 REAL,
trajectory TEXT,
hardness TEXT,
location INTEGER,
batSide TEXT,
pitchHand TEXT,
menOnBase TEXT,
coordX REAL,
coordY REAL,
HM4 TEXT,
HM8 TEXT
);