DROP TABLE IF EXISTS agg_batting_split_stats;

CREATE TABLE IF NOT EXISTS agg_batting_split_stats (
    -- Dimensions
    majorLeagueId       INTEGER,
    seasonId            INTEGER,
    gameType2           TEXT,
    teamId              INTEGER,
    teamType            TEXT,
    playerId            INTEGER,
    venueId             INTEGER,
    officialId          INTEGER,
    opposingTeamId      INTEGER,
    batSide             TEXT,
    pitchHand           TEXT,
    menOnBase           TEXT,
    atbats              INTEGER,
    balks               INTEGER,
    batterInterferences INTEGER,
    bunts               INTEGER,
    catcherInterferences INTEGER,
    doubles             INTEGER,
    fanInterferences    INTEGER,
    fieldErrors         INTEGER,
    fieldersChoice      INTEGER,
    flyouts             INTEGER,
    forceOuts           INTEGER,
    games               INTEGER,
    groundedIntoDoublePlays INTEGER,
    groundedIntoTriplePlays INTEGER,
    groundOuts          INTEGER,
    hitByPitch          INTEGER,
    hits                INTEGER,
    homeRuns            INTEGER,
    intentionalWalks    INTEGER,
    lineOuts            INTEGER,
    passedBalls         INTEGER,
    popOuts             INTEGER,
    runsBattedIn        INTEGER,
    sacBunts            INTEGER,
    sacFlies            INTEGER,
    singles             INTEGER,
    strikeOuts          INTEGER,
    triples             INTEGER,
    walks               INTEGER,
    wildPitches         INTEGER,
    balls               INTEGER,
    ballsPitchOut       INTEGER,
    ballsInDirt         INTEGER,
    intentBalls         INTEGER,
    fouls               INTEGER,
    foulBunts           INTEGER,
    foulTips            INTEGER,
    foulPitchOuts       INTEGER,
    hitIntoPlay         INTEGER,
    pitches             INTEGER,
    pitchOuts           INTEGER,
    strikes             INTEGER,
    strikesCalled       INTEGER,
    strikesPitchOuts    INTEGER,
    missedBunts         INTEGER,
    swingAndMissStrikes INTEGER,
    swingsPitchOuts     INTEGER,
    swings              INTEGER,
    swingsZeroAndZero   INTEGER,
    swingsZeroAndOne    INTEGER,
    swingsZeroAndTwo    INTEGER,
    swingsOneAndZero    INTEGER,
    swingsOneAndOne     INTEGER,
    swingsOneAndTwo     INTEGER,
    swingsTwoAndZero    INTEGER,
    swingsTwoAndOne     INTEGER,
    swingsTwoAndTwo     INTEGER,
    swingsThreeAndZero  INTEGER,
    swingsThreeAndOne   INTEGER,
    swingsThreeAndTwo   INTEGER,
    flyBalls            INTEGER,
    groundBalls         INTEGER,
    lineDrives          INTEGER,
    popUps              INTEGER,
    groundBunts         INTEGER,
    popupBunts          INTEGER,
    lineDriveBunts      INTEGER,
    groupingId          INTEGER,
    groupingDescription TEXT
);

CREATE INDEX IF NOT EXISTS idx_agg_batting_split_stats_groupingId ON agg_batting_split_stats (groupingId);
CREATE INDEX IF NOT EXISTS idx_agg_batting_split_stats_groupingDescription ON agg_batting_split_stats (groupingDescription);
CREATE INDEX IF NOT EXISTS idx_agg_batting_split_stats_majorLeagueId ON agg_batting_split_stats (majorLeagueId);
CREATE INDEX IF NOT EXISTS idx_agg_batting_split_stats_seasonId ON agg_batting_split_stats (seasonId);
CREATE INDEX IF NOT EXISTS idx_agg_batting_split_stats_teamId ON agg_batting_split_stats (teamId);
CREATE INDEX IF NOT EXISTS idx_agg_batting_split_stats_playerId ON agg_batting_split_stats (playerId);
CREATE INDEX IF NOT EXISTS idx_agg_batting_split_stats_venueId ON agg_batting_split_stats (venueId);
CREATE INDEX IF NOT EXISTS idx_agg_batting_split_stats_officialId ON agg_batting_split_stats (officialId);
CREATE INDEX IF NOT EXISTS idx_agg_batting_split_stats_opposingTeamId    ON agg_batting_split_stats (opposingTeamId);
